    !pip install requests
    !pip install beautifulsoup4
    !pip install lxml
    !pip install pandas
    !pip install matplotlib
    !pip install seaborn

In [2]:
url = 'https://www.worldometers.info/coronavirus/'
import requests
html = requests.get(url).content

In [3]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(html,'html.parser')

In [4]:
soup

<!DOCTYPE html>

<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>COVID - Coronavirus Statistics - Worldometer</title>
<meta content="Daily and weekly updated statistics tracking the number of COVID-19 cases, recovered, and deaths. Historical data with cumulative charts, graphs, and updates." name="description"/>
<!-- Favicon -->
<link href="/favicon/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/favicon/manifest.json" rel="manifest"/>
<meta content="#ffffff" name="msapplication-TileColor"/>
<meta content="/favicon/ms-icon-144x144.png" name="msapplication-TileImage"/>
<meta content="#ffffff" name="theme-color"/>
<!-- og image -->
<meta content="http://www.worldometers.info/img/worldometers-fb.jpg" property="og:image">
<!-- Bootstrap -->
<link href="/css/bootstrap.min.css" rel="stylesheet"/>
<link href="/wm16.css" rel="stylesheet"/>
<!-- font awesome -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>-->
<script src="/js/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="/js/ie10-viewport-bug-workaround.js"></script>
<!-- tables
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/s/bs-3.3.5/dt-1.10.10,fh-3.1.0,r-2.0.0/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/s/bs-3.3.5/dt-1.10.10,fh-3.1.0,r-2.0.0/datatables.min.js"></script>


<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.css"/>

<script type="text/javascript" src="https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.js"></script>
 -->
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css">
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#example2').dataTable( {
        "scrollCollapse": true,
		"sDom": '<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#table3').dataTable( {
        "scrollCollapse": true,
				 "order": [[ 1, 'desc' ]],
		"sDom": '<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#example').dataTable( {
        "scrollCollapse": true,
		"searching": false,

		"sDom": '<"top">rt<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
$(document).ready(function() {
	$('#popbycountry').dataTable();
} );
	</script>
<!-- FREESTAR -->
<script data-cfasync="false" type="text/javascript">
  var freestar = freestar || {};
  freestar.hitTime = Date.now();
  freestar.queue = freestar.queue || [];
  freestar.config = freestar.config || {};
  freestar.debug = window.location.search.indexOf('fsdebug') === -1 ? false : true;
  freestar.config.enabled_slots = [];
  !function(a,b){var c=b.getElementsByTagName("script")[0],d=b.createElement("script"),e="https://a.pub.network/worldometers-info";e+=freestar.debug?"/qa/pubfig.min.js":"/pubfig.min.js",d.async=!0,d.src=e,c.parentNode.insertBefore(d,c)}(window,document);
</script>
</link></meta></head>
<body>
<!-- Quantcast Choice. Consent Manager Tag v2.0 (for TCF 2.0) -->
<!--
<script type="text/javascript" async=true>
(function() {
  var host = 'worldometers.info';
  var element = document.createElement('script');
  var firstScript = document.getElementsByTagName('script')[0];
  var url = 'https://quantcast.mgr.consensu.org'
    .concat('/choice/', 'Pd9JxUkvV0m7q', '/', host, '/choice.js');
  var uspTries = 0;
  var uspTriesLimit = 3;
  element.async = true;
  element.type = 'text/javascript';
  element.src = url;

  firstScript.parentNode.insertBefore(element, firstScript);

  function makeStub() {
    var TCF_LOCATOR_NAME = '__tcfapiLocator';
    var queue = [];
    var win = window;
    var cmpFrame;

    function addFrame() {
      var doc = win.document;
      var otherCMP = !!(win.frames[TCF_LOCATOR_NAME]);

      if (!otherCMP) {
        if (doc.body) {
          var iframe = doc.createElement('iframe');

          iframe.style.cssText = 'display:none';
          iframe.name = TCF_LOCATOR_NAME;
          doc.body.appendChild(iframe);
        } else {
          setTimeout(addFrame, 5);
        }
      }
      return !otherCMP;
    }

    function tcfAPIHandler() {
      var gdprApplies;
      var args = arguments;

      if (!args.length) {
        return queue;
      } else if (args[0] === 'setGdprApplies') {
        if (
          args.length > 3 &&
          args[2] === 2 &&
          typeof args[3] === 'boolean'
        ) {
          gdprApplies = args[3];
          if (typeof args[2] === 'function') {
            args[2]('set', true);
          }
        }
      } else if (args[0] === 'ping') {
        var retr = {
          gdprApplies: gdprApplies,
          cmpLoaded: false,
          cmpStatus: 'stub'
        };

        if (typeof args[2] === 'function') {
          args[2](retr);
        }
      } else {
        queue.push(args);
      }
    }

    function postMessageEventHandler(event) {
      var msgIsString = typeof event.data === 'string';
      var json = {};

      try {
        if (msgIsString) {
          json = JSON.parse(event.data);
        } else {
          json = event.data;
        }
      } catch (ignore) {}

      var payload = json.__tcfapiCall;

      if (payload) {
        window.__tcfapi(
          payload.command,
          payload.version,
          function(retValue, success) {
            var returnMsg = {
              __tcfapiReturn: {
                returnValue: retValue,
                success: success,
                callId: payload.callId
              }
            };
            if (msgIsString) {
              returnMsg = JSON.stringify(returnMsg);
            }
            event.source.postMessage(returnMsg, '*');
          },
          payload.parameter
        );
      }
    }

    while (win) {
      try {
        if (win.frames[TCF_LOCATOR_NAME]) {
          cmpFrame = win;
          break;
        }
      } catch (ignore) {}

      if (win === window.top) {
        break;
      }
      win = win.parent;
    }
    if (!cmpFrame) {
      addFrame();
      win.__tcfapi = tcfAPIHandler;
      win.addEventListener('message', postMessageEventHandler, false);
    }
  };

  makeStub();

  var uspStubFunction = function() {
    var arg = arguments;
    if (typeof window.__uspapi !== uspStubFunction) {
      setTimeout(function() {
        if (typeof window.__uspapi !== 'undefined') {
          window.__uspapi.apply(window.__uspapi, arg);
        }
      }, 500);
    }
  };

  var checkIfUspIsReady = function() {
    uspTries++;
    if (window.__uspapi === uspStubFunction && uspTries < uspTriesLimit) {
      console.warn('USP is not accessible');
    } else {
      clearInterval(uspInterval);
    }
  };

  if (typeof window.__uspapi === 'undefined') {
    window.__uspapi = uspStubFunction;
    var uspInterval = setInterval(checkIfUspIsReady, 6000);
  }
})();
</script>
-->
<!-- End Quantcast Choice. Consent Manager Tag v2.0 (for TCF 2.0) -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-1438574-2', 'auto');
  ga('send', 'pageview');
</script>
<!-- GA wm old (info) -->
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-1438574-30"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-1438574-30');
</script>
<!-- GDPR consent -->
<link href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" rel="stylesheet" type="text/css">
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#efefef",
      "text": "#404040"
    },
    "button": {
      "background": "#8ec760",
      "text": "#ffffff"
    }
  },
  "theme": "classic",
  "content": {
    "href": "http://www.worldometers.info/policy/"
  }
})});
</script>
<style type="text/css">
    .style1 {
        color: #666666
    }
</style>
<div class="navbar navbar-default">
<div class="container">
<div class="navbar-header">
<div class="logo"><a class="navbar-brand" href="/"><img border="0" src="/img/worldometers-logo.gif" title="Worldometer"/></a></div>
<button class="navbar-toggle" data-target="#navbar-main" data-toggle="collapse" type="button">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
</div>
<div class="navbar-collapse collapse" id="navbar-main">
<ul class="nav navbar-nav">
<li><a href="/coronavirus/">Coronavirus</a></li>
<li><a href="/population/">Population</a></li>
</ul>
</div>
</div>
</div>
<!-- MAIN -->
<div class="container">
<!-- TOP AD -->
<div class="row">
<div style="text-align:left; margin-bottom:10px">
<script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- wm_top970 -->
<ins class="adsbygoogle" data-ad-client="ca-pub-3701697624350410" data-ad-slot="3287840995" style="display:inline-block;width:970px;height:90px"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
</div>
<!-- TOP AD -->
<!-- MAIN  -->
<!-- CENTER -->
<div class="row"> <div class="col-md-8">
<!-- *** CONTENT A *** -->
<div class="content-inner">
<style>
    .number-table {
        font-size: 20px;
        font-weight: bold
    }

    .number-table-main {
        font-size: 24px;
        font-weight: bold
    }
</style>
<!-- charts -->
<script src="/js/highcharts.js"></script>
<style type="text/css">
    .source {}

    .style2 {
        color: #FF0000
    }

    .style4 {
        color: #FF0000;
        font-weight: bold;
    }

    .style6 {
        font-size: 12px;
        color: #bbb;
        font-weight: bold;
    }

    .source1 {
        font-size: 12px;
        color: #bbb;
    }

    .source1 {
        font-size: 12px;
        color: #bbb;
    }

    .source11 {
        font-size: 12px;
        color: #bbb;
    }

    .source111 {}

    .source1111 {
        font-size: 12px;
        color: #bbb;
    }


    .new_badge {

        position: absolute;
        font-size: 12px;
        top: -5px;
        right: -26px;
        background-color: #8ACA2B;
        color: white;
        padding-left: 4px;
        padding-right: 4px;
        padding-top: 2px;
        padding-bottom: 2px;
        border-radius: 4px;
        ;
    }

    .new_badge_link {

        background-color: #8ACA2B;
        color: white !important;
        padding-left: 4px;
        padding-right: 4px;
        padding-top: 2px;
        padding-bottom: 2px;
        border-radius: 4px;
        ;
    }
</style>
<div class="label-counter" id="page-top">COVID-19 Coronavirus Pandemic</div>
<div style="font-size:13px; color:#999; margin-top:5px; text-align:center">Last updated: April 16, 2023, 01:10 GMT</div>
<div style="margin-top:20px; text-align:center; font-size:14px"><a class="new_badge_link" href="/coronavirus/weekly-trends/" style="display: inline-block; position:relative;">Weekly Trends</a> - <a href="/coronavirus/worldwide-graphs/">Graphs</a> - <a href="#countries">Countries</a> - <a href="#news">News</a></div>
<div id="maincounter-wrap" style="margin-top:15px">
<h1>Coronavirus Cases:</h1>
<div class="maincounter-number">
<span style="color:#aaa">685,600,869        </span>
</div>
</div>
<div style="text-align:center "><a href="#countries">view by country</a></div>
<div id="maincounter-wrap" style="margin-top:15px">
<h1>Deaths:</h1>
<div class="maincounter-number">
<span>6,842,360</span>
</div>
</div>
<div id="maincounter-wrap" style="margin-top:15px;">
<h1>Recovered:</h1>
<div class="maincounter-number" style="color:#8ACA2B ">
<span>658,338,114</span>
</div>
</div>
<div style="margin-top:50px;"></div>
<!-- START -->
<style>
    .panel_flip {
        position: relative;
        height: 100%;
    }

    .panel_front {

        height: inherit;
        position: absolute;
        top: 0;
        -webkit-transform: rotateX(0deg) rotateY(0deg);
        -moz-transform: rotateX(0deg) rotateY(0deg);
        -webkit-transform-style: preserve-3d;
        -moz-transform-style: preserve-3d;
        -webkit-backface-visibility: hidden;
        -moz-backface-visibility: hidden;
        -webkit-transition: all .4s ease-in-out;
        -moz-transition: all .4s ease-in-out;
        -ms-transition: all .4s ease-in-out;
        -o-transition: all .4s ease-in-out;
        transition: all .4s ease-in-out;
    }

    .panel_back {

        height: inherit;
        position: absolute;
        top: 0;
        -webkit-transform: rotateY(-180deg);
        -moz-transform: rotateY(-180deg);
        -webkit-transform-style: preserve-3d;
        -moz-transform-style: preserve-3d;
        -webkit-backface-visibility: hidden;
        -moz-backface-visibility: hidden;
        -webkit-transition: all .4s ease-in-out;
        -moz-transition: all .4s ease-in-out;
        -ms-transition: all .4s ease-in-out;
        -o-transition: all .4s ease-in-out;
        transition: all .4s ease-in-out;
    }

    .panel_flip.flip .panel_front {

        z-index: 900;
        -webkit-transform: rotateY(180deg);
        -moz-transform: rotateY(180deg);
    }

    .panel_flip.flip .panel_back {

        z-index: 1000;
        -webkit-transform: rotateX(0deg) rotateY(0deg);
        -moz-transform: rotateX(0deg) rotateY(0deg);
    }

    .collapse_button {

        position: absolute;
        right: 10px;
        pointer-events: none;
        color: #70757a !important;
        height: 24px;
        width: 24px;
        line-height: 24px;
    }

    .collapse_button svg {
        display: block;
        height: 100%;
        width: 100%;
        fill: currentColor;
    }

    .rotate_180 {

        transform: rotate(180deg);
    }

    .panel_clickable {

        cursor: pointer;
    }
</style>
<script>
    var do_not_slide = false;
    $(function() {

        $('.flip_cases_front').on('click', function() {


            $(this).parent().parent().addClass('flip');
        });

        $('.flip_cases_back').on('click', function() {


            $(this).parent().parent().removeClass('flip');
        });


        $('.collapse').on('show.bs.collapse', function(el) {


            var collapse_button = $(el.target).parent().find('.collapse_button');
            collapse_button.addClass('rotate_180');

            if (do_not_slide) {

                return;
            }

            do_not_slide = true;
            if ($(el.target).attr('id') == 'panel_active') {

                $('#panel_closed').collapse('show');
            } else {

                $('#panel_active').collapse('show');
            }

            do_not_slide = false;
        });

        $('.collapse').on('hide.bs.collapse', function(el) {

            var collapse_button = $(el.target).parent().find('.collapse_button');
            collapse_button.removeClass('rotate_180');


            if (do_not_slide) {

                return;
            }


            do_not_slide = true;
            if ($(el.target).attr('id') == 'panel_active') {

                $('#panel_closed').collapse('hide');
            } else {

                $('#panel_active').collapse('hide');
            }

            do_not_slide = false;

        });



    });
</script>
<div class="col-md-6">
<div class="panel panel-default">
<div aria-controls="panel_active" aria-expanded="false" class="panel_clickable panel-heading" data-toggle="collapse" href="#panel_active" style="text-align:center;position:relative;">
<span class="panel-title" style="font-size:18px; text-transform:uppercase; font-weight:100">
                    Active Cases
                </span>
<span class="collapse_button"><svg focusable="false" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
<path d="M7.41 8.59L12 13.17l4.59-4.58L18 10l-6 6-6-6 1.41-1.41z"></path>
</svg></span>
</div>
<div class="collapse" id="panel_active">
<div class="panel-body" style="text-align:center;min-height:220px;">
<div class="panel_flip">
<div class="panel_front" style="width:100%;height:100%;">
<div class="number-table-main">20,420,395</div>
<div style="font-size:13.5px">Currently Infected Patients</div>
<div style="padding-top:20px;position:relative;text-align:center; ">
<div style="float:left; text-align:center">
<span class="number-table" style="color:#8080FF">20,380,883</span> (<strong>99.8</strong>%)

                                    <div style="font-size:13px">in Mild Condition</div><br/>
</div>
<div style="float:right; text-align:center"><span class="number-table" style="color:red ">39,512</span> (<strong>0.2</strong>%)
                                    <div style="font-size:13px">Serious or Critical</div><br/>
</div>
</div>
<a class="flip_cases_front" href="javascript: void(0);" style="clear: both;display: block;padding-top:20px;width:100%;">Show Graph</a>
</div>
<div class="panel_back" style="width:100%;height:100%;">
<div id="total-currently-infected-linear"></div>

In [5]:
tbody = soup.find('tbody')

In [6]:
tbody

<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>125,978,653</td>
<td></td>
<td>1,625,792</td>
<td></td>
<td>121,651,500</td>
<td>+1,255</td>
<td>2,701,361</td>
<td>6,802</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>215,934,854</td>
<td>+20</td>
<td>1,542,714</td>
<td></td>
<td>200,165,380</td>
<td>+13,135</td>
<td>14,226,760</td>
<td>15,510</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>248,333,948</td>
<td></td>
<td>2,034,851</td>
<td></td>
<td>244,104,876</td>
<td>+2,659</td>
<td>2,194,221</td>
<td>6,415</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>68,452,197</td>
<td></td>
<td>1,353,366</td>
<td></td>
<td>66,431,785</td>
<td>+327</td>
<td>667,046</td>
<td>10,166</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>14,084,808</td>
<td></td>
<td>26,940</td>
<td></td>
<td>13,901,165</td>
<td></td>
<td>156,703</td>
<td>71</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>12,815,688</td>
<td></td>
<td>258,682</td>
<td></td>
<td>12,082,702</td>
<td></td>
<td>474,304</td>
<td>548</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>706</td>
<td></td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>685,600,869</td>
<td>+20</td>
<td>6,842,360</td>
<td>0</td>
<td>658,338,114</td>
<td>+17,376</td>
<td>20,420,395</td>
<td>39,512</td>
<td>87,956</td>
<td>877.8</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">106,464,679</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">1,158,158                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">104,311,698</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">994,823</td>
<td style="font-weight: bold; text-align:right">1,636</td>
<td style="font-weight: bold; text-align:right">317,990</td>
<td style="font-weight: bold; text-align:right">3,459</td>
<td style="font-weight: bold; text-align:right">1,175,946,071</td>
<td style="font-weight: bold; text-align:right">3,512,328</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>289</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,971</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">44,808,022</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">531,091                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">44,223,211</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">53,720</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">31,855</td>
<td style="font-weight: bold; text-align:right">378</td>
<td style="font-weight: bold; text-align:right">923,497,482</td>
<td style="font-weight: bold; text-align:right">656,531</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>31</td><td>2,649</td><td>2</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">38</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">39,896,203</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">166,024                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">39,592,740</span></td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">137,439</td>
<td style="font-weight: bold; text-align:right">869</td>
<td style="font-weight: bold; text-align:right">608,317</td>
<td style="font-weight: bold; text-align:right">2,531</td>
<td style="font-weight: bold; text-align:right">271,490,188</td>
<td style="font-weight: bold; text-align:right">4,139,547</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>395</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,096</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">38,382,386</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">171,992                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">38,149,200</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">61,194</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">457,567</td>
<td style="font-weight: bold; text-align:right">2,050</td>
<td style="font-weight: bold; text-align:right">122,332,384</td>
<td style="font-weight: bold; text-align:right">1,458,359</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>488</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">730</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">37,358,092</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">700,811                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">36,249,161</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">408,120</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">173,473</td>
<td style="font-weight: bold; text-align:right">3,254</td>
<td style="font-weight: bold; text-align:right">63,776,166</td>
<td style="font-weight: bold; text-align:right">296,146</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>307</td><td>3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,895</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
<td style="font-weight: bold; text-align:right">33,573,695</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">74,220                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">21,725,273</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">11,774,202</td>
<td style="font-weight: bold; text-align:right">53</td>
<td style="font-weight: bold; text-align:right">267,339</td>
<td style="font-weight: bold; text-align:right">591</td>
<td style="font-weight: bold; text-align:right">99,119,701</td>
<td style="font-weight: bold; text-align:right">789,265</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>4</td><td>1,692</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">93,755</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
<td style="font-weight: bold; text-align:right">30,978,954</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">34,368                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">30,764,355</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+13,132</td>
<td style="text-align:right;font-weight:bold;">180,231</td>
<td style="font-weight: bold; text-align:right">114</td>
<td style="font-weight: bold; text-align:right">603,526</td>
<td style="font-weight: bold; text-align:right">670</td>
<td style="font-weight: bold; text-align:right">15,804,065</td>
<td style="font-weight: bold; text-align:right">307,892</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>1,494</td><td>3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">3,511</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">25,737,170</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">189,391                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">25,413,901</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">133,878</td>
<td style="font-weight: bold; text-align:right">83</td>
<td style="font-weight: bold; text-align:right">427,082</td>
<td style="font-weight: bold; text-align:right">3,143</td>
<td style="font-weight: bold; text-align:right">270,717,229</td>
<td style="font-weight: bold; text-align:right">4,492,280</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>318</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,222</td>
</tr>
<tr style="background-color:#F0F0F0">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">24,448,729</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">209,396                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">24,239,333</span></td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">0</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">356,927</td>
<td style="font-weight: bold; text-align:right">3,057</td>
<td style="font-weight: bold; text-align:right">522,526,476</td>
<td style="font-weight: bold; text-align:right">7,628,357</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>327</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">22,758,243</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">397,790                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">22,144,313</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">216,140</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">156,086</td>
<td style="font-weight: bold; text-align:right">2,728</td>
<td style="font-weight: bold; text-align:right">273,400,000</td>
<td style="font-weight: bold; text-align:right">1,875,095</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>367</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,482</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
<td style="font-weight: bold; text-align:right">17,232,066</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">102,174                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">201,399</td>
<td style="font-weight: bold; text-align:right">1,194</td>
<td style="font-weight: bold; text-align:right">162,743,369</td>
<td style="font-weight: bold; text-align:right">1,902,052</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">85,561,976</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>5</td><td>837</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>

In [7]:
table_rows = tbody.find_all('tr')

In [8]:
table_rows

[<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>North America</nobr>
 </td>
 <td>125,978,653</td>
 <td></td>
 <td>1,625,792</td>
 <td></td>
 <td>121,651,500</td>
 <td>+1,255</td>
 <td>2,701,361</td>
 <td>6,802</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="North America" style="display:none;">North America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Asia</nobr>
 </td>
 <td>215,934,854</td>
 <td>+20</td>
 <td>1,542,714</td>
 <td></td>
 <td>200,165,380</td>
 <td>+13,135</td>
 <td>14,226,760</td>
 <td>15,510</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Asia" style="display:none;">Asia</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Europe</nobr>
 </td>
 <td>248,333,948</td>
 <td></td>
 <td>2,034,851</td>
 <td></td>
 <td>244,104,876</td>
 <td>+2,659</td>
 <td>2,194,221</td>
 <td>6,415</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Europe" style="display:none;">Europe</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="South America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>South America</nobr>
 </td>
 <td>68,452,197</td>
 <td></td>
 <td>1,353,366</td>
 <td></td>
 <td>66,431,785</td>
 <td>+327</td>
 <td>667,046</td>
 <td>10,166</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="South America" style="display:none;">South America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Oceania</nobr>
 </td>
 <td>14,084,808</td>
 <td></td>
 <td>26,940</td>
 <td></td>
 <td>13,901,165</td>
 <td></td>
 <td>156,703</td>
 <td>71</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Africa</nobr>
 </td>
 <td>12,815,688</td>
 <td></td>
 <td>258,682</td>
 <td></td>
 <td>12,082,702</td>
 <td></td>
 <td>474,304</td>
 <td>548</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Africa" style="display:none;">Africa</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr></nobr>
 </td>
 <td>721</td>
 <td></td>
 <td>15</td>
 <td></td>
 <td>706</td>
 <td></td>
 <td>0</td>
 <td>0</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="" style="display:none;"></td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world">
 <td></td>
 <td style="text-align:left;">World</td>
 <td>685,600,869</td>
 <td>+20</td>
 <td>6,842,360</td>
 <td>0</td>
 <td>658,338,114</td>
 <td>+17,376</td>
 <td>20,420,395</td>
 <td>39,512</td>
 <td>87,956</td>
 <td>877.8</td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="all" style="display:none">All</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
 <td style="font-weight: bold; text-align:right">106,464,679</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">1,158,158                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">104,311,698</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">994,823</td>
 <td style="font-weight: bold; text-align:right">1,636</td>
 <td style="font-weight: bold; text-align:right">317,990</td>
 <td style="font-weight: bold; text-align:right">3,459</td>
 <td style="font-weight: bold; text-align:right">1,175,946,071</td>
 <td style="font-weight: bold; text-align:right">3,512,328</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
 <td data-continent="North America" style="display:none">North America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>289</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">2,971</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
 <td style="font-weight: bold; text-align:right">44,808,022</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">531,091                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">44,223,211</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">53,720</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">31,855</td>
 <td style="font-weight: bold; text-align:right">378</td>
 <td style="font-weight: bold; text-align:right">923,497,482</td>
 <td style="font-weight: bold; text-align:right">656,531</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>31</td><td>2,649</td><td>2</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">38</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
 <td style="font-weight: bold; text-align:right">39,896,203</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">166,024                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">39,592,740</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">137,439</td>
 <td style="font-weight: bold; text-align:right">869</td>
 <td style="font-weight: bold; text-align:right">608,317</td>
 <td style="font-weight: bold; text-align:right">2,531</td>
 <td style="font-weight: bold; text-align:right">271,490,188</td>
 <td style="font-weight: bold; text-align:right">4,139,547</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>395</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">2,096</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
 <td style="font-weight: bold; text-align:right">38,382,386</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">171,992                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">38,149,200</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">61,194</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">457,567</td>
 <td style="font-weight: bold; text-align:right">2,050</td>
 <td style="font-weight: bold; text-align:right">122,332,384</td>
 <td style="font-weight: bold; text-align:right">1,458,359</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>488</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">730</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
 <td style="font-weight: bold; text-align:right">37,358,092</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">700,811                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">36,249,161</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">408,120</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">173,473</td>
 <td style="font-weight: bold; text-align:right">3,254</td>
 <td style="font-weight: bold; text-align:right">63,776,166</td>
 <td style="font-weight: bold; text-align:right">296,146</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>6</td><td>307</td><td>3</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">1,895</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
 <td style="font-weight: bold; text-align:right">33,573,695</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">74,220                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">21,725,273</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">11,774,202</td>
 <td style="font-weight: bold; text-align:right">53</td>
 <td style="font-weight: bold; text-align:right">267,339</td>
 <td style="font-weight: bold; text-align:right">591</td>
 <td style="font-weight: bold; text-align:right">99,119,701</td>
 <td style="font-weight: bold; text-align:right">789,265</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>4</td><td>1,692</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">93,755</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
 <td style="font-weight: bold; text-align:right">30,978,954</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">34,368                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">30,764,355</span></td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+13,132</td>
 <td style="text-align:right;font-weight:bold;">180,231</td>
 <td style="font-weight: bold; text-align:right">114</td>
 <td style="font-weight: bold; text-align:right">603,526</td>
 <td style="font-weight: bold; text-align:right">670</td>
 <td style="font-weight: bold; text-align:right">15,804,065</td>
 <td style="font-weight: bold; text-align:right">307,892</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>1,494</td><td>3</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">3,511</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
 <td style="font-weight: bold; text-align:right">25,737,170</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">189,391                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">25,413,901</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">133,878</td>
 <td style="font-weight: bold; text-align:right">83</td>
 <td style="font-weight: bold; text-align:right">427,082</td>
 <td style="font-weight: bold; text-align:right">3,143</td>
 <td style="font-weight: bold; text-align:right">270,717,229</td>
 <td style="font-weight: bold; text-align:right">4,492,280</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>318</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">2,222</td>
 </tr>,
 <tr style="background-color:#F0F0F0">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
 <td style="font-weight: bold; text-align:right">24,448,729</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">209,396                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">24,239,333</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">0</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">356,927</td>
 <td style="font-weight: bold; text-align:right">3,057</td>
 <td style="font-weight: bold; text-align:right">522,526,476</td>
 <td style="font-weight: bold; text-align:right">7,628,357</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>327</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
 <td style="font-weight: bold; text-align:right">22,758,243</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">397,790                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">22,144,313</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">216,140</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">156,086</td>
 <td style="font-weight: bold; text-align:right">2,728</td>
 <td style="font-weight: bold; text-align:right">273,400,000</td>
 <td style="font-weight: bold; text-align:right">1,875,095</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>6</td><td>367</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">1,482</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
 <td style="font-weight: bold; text-align:right">17,232,066</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">102,174                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right;">N/A</td>
 <td style="text-align:right;font-weight:bold;">N/A</td>
 <td style="font-weight: bold; text-align:right"></td>

In [9]:
table_rows[8]

<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">106,464,679</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">1,158,158                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">104,311,698</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">994,823</td>
<td style="font-weight: bold; text-align:right">1,636</td>
<td style="font-weight: bold; text-align:right">317,990</td>
<td style="font-weight: bold; text-align:right">3,459</td>
<td style="font-weight: bold; text-align:right">1,175,946,071</td>
<td style="font-weight: bold; text-align:right">3,512,328</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>289</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,971</td>
</tr>

In [10]:
for i in range(8,len(table_rows)):
    td = table_rows[i].find_all('td')
    for table_data in td:
        print(table_data.text)

1
USA
106,464,679

1,158,158

104,311,698

994,823
1,636
317,990
3,459
1,175,946,071
3,512,328
334,805,269
North America
3
289
0


2,971
2
India
44,808,022

531,091

44,223,211

53,720
N/A
31,855
378
923,497,482
656,531
1,406,631,776
Asia
31
2,649
2


38
3
France
39,896,203

166,024

39,592,740

137,439
869
608,317
2,531
271,490,188
4,139,547
65,584,518
Europe
2
395
0


2,096
4
Germany
38,382,386

171,992

38,149,200

61,194
N/A
457,567
2,050
122,332,384
1,458,359
83,883,596
Europe
2
488
1


730
5
Brazil
37,358,092

700,811

36,249,161

408,120
N/A
173,473
3,254
63,776,166
296,146
215,353,593
South America
6
307
3


1,895
6
Japan
33,573,695

74,220

21,725,273

11,774,202
53
267,339
591
99,119,701
789,265
125,584,838
Asia
4
1,692
1


93,755
7
S. Korea
30,978,954

34,368

30,764,355
+13,132
180,231
114
603,526
670
15,804,065
307,892
51,329,899
Asia
2
1,494
3


3,511
8
Italy
25,737,170

189,391

25,413,901

133,878
83
427,082
3,143
270,717,229
4,492,280
60,262,770
Europe
2
318
0


2,222
9
UK
24,448,729

209,396

24,239,333

0
N/A
356,927
3,057
522,526,476
7,628,357
68,497,907
Europe
3
327
0



10
Russia
22,758,243

397,790

22,144,313

216,140
N/A
156,086
2,728
273,400,000
1,875,095
145,805,947
Europe
6
367
1


1,482
11
Turkey
17,232,066

102,174

N/A
N/A
N/A

201,399
1,194
162,743,369
1,902,052
85,561,976
Asia
5
837
1


4,024
12
Spain
13,813,830

120,606

13,659,874

33,350
231
295,678
2,582
471,036,328
10,082,298
46,719,142
Europe
3
387
0


714
13
Vietnam
11,530,356

43,186

10,615,343

871,827
10
116,523
436
85,826,548
867,342
98,953,541
Asia
9
2,291
1


8,810
14
Australia
11,381,793

20,049

11,314,115

47,629
43
436,606
769
78,835,048
3,024,116
26,068,792
Australia/Oceania
2
1,300
0


1,827
15
Taiwan
10,239,998

19,005

10,220,993
+4
0

428,656
796
30,742,304
1,286,903
23,888,595
Asia
2
1,257
1



16
Argentina
10,044,957

130,472

9,914,485

0
363
218,320
2,836
35,716,069
776,264
46,010,234
South America
5
353
1



17
Netherlands
8,610,372

22,992

8,582,526
+437
4,854
53
500,270
1,336
25,984,435
1,509,718
17,211,447
Europe
2
749
1


282
18
Iran
7,597,982

145,571

7,342,490

109,921
407
88,325
1,692
55,353,767
643,478
86,022,837
Asia
11
591
2


1,278
19
Mexico
7,563,576

333,669

6,809,445

420,462
N/A
57,490
2,536
19,835,770
150,770
131,562,772
North America
17
394
7


3,196
20
Indonesia
6,756,541

161,116

6,586,736

8,689
N/A
24,205
577
114,158,919
408,975
279,134,505
Asia
41
1,733
2


31
21
Poland
6,508,636

119,480

5,335,940

1,053,216
696
172,461
3,166
38,606,044
1,022,953
37,739,785
Europe
6
316
1


27,907
22
Colombia
6,363,544

142,698

6,186,501

34,345
342
123,533
2,770
36,951,507
717,327
51,512,762
South America
8
361
1


667
23
Austria
6,052,650

22,276

6,016,085

14,289
55
667,569
2,457
211,273,524
23,302,116
9,066,710
Europe
1
407
0


1,576
24
Greece
5,972,760

36,629

5,927,050
+1,965
9,081
115
578,944
3,550
102,228,365
9,909,078
10,316,637
Europe
2
282
0


880
25
Portugal
5,577,825

26,480

5,545,402

5,943
61
550,050
2,611
46,065,483
4,542,692
10,140,570
Europe
2
383
0


586
26
Ukraine
5,484,936

111,789

5,334,190

38,957

126,989
2,588
32,603,805
754,855
43,192,122
Europe
8
386
1


902
27
Chile
5,278,252

64,497

5,211,301

2,454
69
274,192
3,350
49,226,745
2,557,208
19,250,195
South America
4
298
0


127
28
Malaysia
5,056,911

36,994

5,006,634

13,283
10
152,403
1,115
68,342,991
2,059,698
33,181,072
Asia
7
897
0


400
29
Israel
4,818,346

12,416

4,798,473

7,457
21
516,657
1,331
41,373,364
4,436,346
9,326,000
Asia
2
751
0


800
30
Belgium
4,786,803

34,166

4,723,282

29,355
43
410,241
2,928
36,973,399
3,168,711
11,668,278
Europe
2
342
0


2,516
31
DPRK
4,772,813

74

4,772,739

0

183,636
3


25,990,679
Asia
5
351,225




32
Thailand
4,728,967

33,940

4,692,636

2,391
N/A
67,481
484
17,270,775
246,450
70,078,203
Asia
15
2,065
4


34
33
Canada
4,641,301

52,247

4,563,303
+1,255
25,751
99
120,904
1,361
66,343,123
1,728,207
38,388,419
North America
8
735
1


671
34
Czechia
4,637,897

42,726

4,591,159

4,012
23
431,963
3,979
57,149,297
5,322,757
10,736,784
Europe
2
251
0


374
35
Peru
4,496,896

219,991

4,273,686
+327
3,219
33
133,502
6,531
38,423,871
1,140,709
33,684,208
South America
7
153
1


96
36
Switzerland
4,400,218

14,452

4,379,844

5,922
39
501,527
1,647
23,833,472
2,716,487
8,773,637
Europe
2
607
0


675
37
Philippines
4,085,539

66,437

4,009,622

9,480
162
36,313
591
34,914,751
310,329
112,508,994
Asia
28
1,693
3


84
38
South Africa
4,075,849

102,595

3,912,506

60,748
192
67,085
1,689
26,795,090
441,027
60,756,135
Africa
15
592
2


1,000
39
Romania
3,380,891

67,961

3,299,960

12,970
132
177,649
3,571
27,131,523
1,425,624
19,031,335
Europe
6
280
1


682
40
Denmark
3,179,563

8,464

3,169,944

1,155
19
544,917
1,451
129,253,612
22,151,623
5,834,950
Europe
2
689
0


198
41
Hong Kong
2,886,633

13,490

2,870,397

2,746
28
379,605
1,774
76,127,725
10,011,143
7,604,299
Asia
3
564
0


361
42
Sweden
2,703,773

23,928

2,676,426
+114
3,419
8
264,584
2,342
19,500,873
1,908,301
10,218,971
Europe
4
427
1


335
43
Serbia
2,527,640

18,002

2,498,044

11,594
13
292,111
2,080
12,708,633
1,468,694
8,653,016
Europe
3
481
1


1,340
44
Iraq
2,465,545

25,375

2,439,497

673
21
58,474
602
19,544,451
463,523
42,164,965
Asia
17
1,662
2


16
45
Singapore
2,314,707

1,727

2,149,583

163,397
2
389,449
291
24,756,666
4,165,302
5,943,546
Asia
3
3,442
0


27,492
46
New Zealand
2,286,481

4,045

2,271,682

10,754

466,800
826
7,768,604
1,586,011
4,898,203
Australia/Oceania
2
1,211
1


2,195
47
Hungary
2,200,211

48,828

2,147,103

4,280
2
229,039
5,083
11,394,556
1,186,160
9,606,259
Europe
4
197
1


446
48
Bangladesh
2,038,091

29,446

1,998,448

10,197
N/A
12,140
175
15,254,399
90,862
167,885,689
Asia
82
5,701
11


61
49
Slovakia
1,866,064

21,141

1,844,330

593
23
341,758
3,872
7,422,919
1,359,461
5,460,193
Europe
3
258
1


109
50
Georgia
1,836,791

17,032

1,776,548

43,211

462,815
4,292
16,920,079
4,263,340
3,968,738
Asia
2
233
0


10,888
51
Jordan
1,746,997

14,122

1,731,007

1,868
59
169,597
1,371
17,201,885
1,669,945
10,300,869
Asia
6
729
1


181
52
Ireland
1,708,933

8,810

1,696,485

3,638
19
340,411
1,755
13,083,449
2,606,161
5,020,199
Europe
3
570
0


725
53
Pakistan
1,580,429
+20
30,655

1,538,689

11,085
15
6,887
134
30,570,862
133,213
229,488,994
Asia
145
7,486
8
0.09

48
54
Norway
1,482,235

5,213

1,475,779

1,243
20
268,941
946
11,002,430
1,996,315
5,511,370
Europe
4
1,057
1


226
55
Finland
1,469,865

9,144

1,456,454
+210
4,267
21
264,604
1,646
12,069,254
2,172,699
5,554,960
Europe
4
607
0


768
56
Kazakhstan
1,410,791

13,848

1,383,020

13,923
24
73,459
721
11,575,012
602,707
19,205,043
Asia
14
1,387
2


725
57
Slovenia
1,342,491

7,100

1,328,006

7,385
8
646,039
3,417
2,847,701
1,370,382
2,078,034
Europe
2
293
1


3,554
58
Lithuania
1,316,799

9,650

1,303,244

3,905
7
494,720
3,625
10,425,065
3,916,682
2,661,708
Europe
2
276
0


1,467
59
Bulgaria
1,302,146

38,288

1,260,996

2,862
40
190,244
5,594
11,151,672
1,629,266
6,844,597
Europe
5
179
1


418
60
Morocco
1,272,733

16,296

1,256,151

286
3
33,694
431
13,001,033
344,191
37,772,756
Africa
30
2,318
3


8
61
Croatia
1,271,276

18,091

1,252,694

491
4
313,177
4,457
5,560,149
1,369,736
4,059,286
Europe
3
224
1


121
62
Guatemala
1,246,722

20,189

1,225,638

895
5
67,086
1,086
7,148,360
384,651
18,584,039
North America
15
921
3


48
63
Lebanon
1,235,804

10,885

1,087,587

137,332
74
184,866
1,628
4,795,578
717,380
6,684,849
Asia
5
614
1


20,544
64
Costa Rica
1,226,315

9,326

860,711

356,278
52
236,633
1,800
4,659,757
899,158
5,182,354
North America
4
556
1


68,748
65
Bolivia
1,196,464

22,375

1,165,163

8,926
220
99,766
1,866
2,705,422
225,590
11,992,656
South America
10
536
4


744
66
Tunisia
1,152,262

29,367

N/A
N/A
N/A
44
95,650
2,438
5,008,040
415,720
12,046,656
Africa
10
410
2


1,070
67
Cuba
1,112,990

8,530

1,104,340

120
2
98,445
754
14,324,663
1,267,036
11,305,652
North America
10
1,325
1


11
68
UAE
1,060,146

2,349

1,041,294

16,503

105,155
233
200,056,552
19,843,366
10,081,785
Asia
10
4,292
0


1,637
69
Ecuador
1,059,529

36,017

1,022,992

520
759
58,494
1,988
3,082,403
170,173
18,113,361
South America
17
503
6


29
70
Uruguay
1,037,095

7,621

1,028,996

478
18
296,651
2,180
6,114,822
1,749,083
3,496,016
South America
3
459
1


137
71
Panama
1,035,357

8,617

1,026,192

548
16
232,823
1,938
7,621,296
1,713,820
4,446,964
North America
4
516
1


123
72
Mongolia
1,007,943

2,179

1,005,732

32
192
298,378
645
4,030,048
1,193,000
3,378,078
Asia
3
1,550
1


9
73
Nepal
1,002,128

12,022

989,729

377

33,155
398
6,026,236
199,375
30,225,582
Asia
30
2,514
5


12
74
Belarus
994,037

7,118

985,592

1,327

105,381
755
13,646,641
1,446,722
9,432,800
Europe
9
1,325
1


141
75
Latvia
977,282

6,302

970,544

436
13
528,593
3,409
7,871,447
4,257,513
1,848,837
Europe
2
293
0


236
76
Saudi Arabia
838,246

9,637

823,911

4,698
90
23,385
269
45,378,829
1,265,977
35,844,909
Asia
43
3,720
1


131
77
Azerbaijan
830,780

10,212

820,094

474

80,657
991
7,575,517
735,472
10,300,205
Asia
12
1,009
1


46
78
Paraguay
809,269

19,906

N/A
N/A
N/A
7
110,770
2,725
2,657,506
363,751
7,305,843
South America
9
367
3


12,462
79
Bahrain
718,724

1,559

716,589

576
2
402,876
874
10,814,786
6,062,158
1,783,983
Asia
2
1,144
0


323
80
Sri Lanka
672,103

16,835

655,253

15

31,151
780
6,486,117
300,619
21,575,842
Asia
32
1,282
3


0.7
81
Kuwait
665,527

2,570

660,237

2,720

151,935
587
8,455,743
1,930,391
4,380,326
Asia
7
1,704
1


621
82
Dominican Republic
660,937

4,384

644,785

11,768
4
59,779
397
3,740,928
338,350
11,056,370
North America
17
2,522
3


1,064
83
Cyprus
656,904

1,350

653,364

2,190
60
536,955
1,103
9,640,118
7,879,860
1,223,387
Asia
2
906
0


1,790
84
Myanmar
634,154

19,490

614,619

45

11,483
353
10,227,586
185,191
55,227,143
Asia
87
2,834
5


0.8
85
Palestine
621,008

5,404

615,445

159
17
116,173
1,011
3,078,533
575,907
5,345,541
Asia
9
989
2


30
86
Moldova
619,510

12,100

504,142

103,268
49
154,369
3,015
3,216,305
801,437
4,013,171
Europe
6
332
1


25,732
87
Estonia
617,222

2,979

524,990

89,253
3

466,917
2,254
3,697,161
2,796,833
1,321,910
Europe
2
444
0


67,518
88
Venezuela
552,512

5,856

546,421

235
31
18,878
200
3,359,014
114,771
29,266,991
South America
53
4,998
9


8
89
Egypt
515,913

24,613

442,182

49,118
122
4,860
232
3,693,367
34,792
106,156,692
Africa
206
4,313
29


463
90
Libya
507,244

6,437

500,792

15

72,044
914
2,483,848
352,782
7,040,745
Africa
14
1,094
3


2
91
Qatar
503,909

690

501,346

1,873
44
169,102
232
4,065,369
1,364,257
2,979,915
Asia
6
4,319
1


629
92
Ethiopia
500,774

7,574

487,838

5,362
1
4,145
63
5,532,785
45,796
120,812,698
Africa
241
15,951
22


44
93
Réunion
486,588

921

418,572

67,095
10
535,854
1,014
1,603,660
1,766,027
908,061
Africa
2
986
1


73,888
94
Honduras
472,485

11,111

N/A
N/A
N/A
105
46,226
1,087
1,650,345
161,462
10,221,247
North America
22
920
6


32,171
95
Armenia
448,707

8,743

435,162

4,802

150,980
2,942
3,242,901
1,091,164
2,971,966
Asia
7
340
1


1,616
96
Bosnia and Herzegovina
402,636

16,328

379,084

7,224

123,914
5,025
1,884,721
580,036
3,249,317
Europe
8
199
2


2,223
97
Oman
399,449

4,628

384,669

10,152
2
75,028
869
25,000,000
4,695,724
5,323,993
Asia
13
1,150
0


1,907
98
North Macedonia
347,672

9,667

337,068

937

167,045
4,645
2,226,216
1,069,626
2,081,304
Europe
6
215
1


450
99
Zambia
343,803

4,058

339,632

113

17,658
208
4,000,548
205,470
19,470,234
Africa
57
4,798
5


6
100
Kenya
342,992

5,688

337,282

22
1
6,101
101
3,967,062
70,569
56,215,221
Africa
164
9,883
14


0.4
101
Albania
334,714

3,602

329,419

1,693

116,773
1,257
1,941,032
677,173
2,866,374
Europe
9
796
1


591
102
Botswana
329,837

2,801

327,027

9
1
135,115
1,147
2,026,898
830,300
2,441,162
Africa
7
872
1


4
103
Luxembourg
297,757

1,133

288,991

7,633

463,528
1,764
4,412,567
6,869,188
642,371
Europe
2
567
0


11,883
104
Montenegro
290,779

2,820

287,276

683
6
463,061
4,491
2,741,050
4,365,077
627,950
Europe
2
223
0


1,088
105
Brunei
284,632

225

243,601

40,806
3
639,004
505
717,784
1,611,437
445,431
Asia
2
1,980
1


91,610
106
Algeria
271,642

6,881

182,916

81,845

5,990
152
230,861
5,091
45,350,148
Africa
167
6,591
196


1,805
107
Nigeria
266,675

3,155

259,953

3,567
11
1,230
15
5,708,974
26,339
216,746,934
Africa
813
68,700
38


16
108
Zimbabwe
264,584

5,685

258,844

55
12
17,258
371
2,525,756
164,744
15,331,428
Africa
58
2,697
6


4
109
Uzbekistan
252,265

1,637

241,486

9,142
23
7,337
48
1,377,915
40,077
34,382,084
Asia
136
21,003
25


266
110
Mozambique
233,334

2,242

228,805

2,287
11
7,052
68
1,371,127
41,437
33,089,461
Africa
142
14,759
24


69
111
Martinique
229,807

1,098

N/A
N/A
N/A
12
614,314
2,935
828,928
2,215,870
374,087
North America
2
341
0


611,101
112
Laos
218,048

758

N/A
N/A
N/A

29,147
101
1,233,207
164,845
7,481,023
Asia
34
9,869
6


28,022
113
Afghanistan
212,605

7,896

192,700

12,009
45
5,217
194
1,224,908
30,056
40,754,388
Asia
192
5,161
33


295
114
Iceland
209,191

229

N/A
N/A
N/A
2
605,661
663
1,996,384
5,780,036
345,393
Europe
2
1,508
0


385,871
115
Kyrgyzstan
206,849

2,991

196,406

7,452
131
30,743
445
1,907,195
283,460
6,728,271
Asia
33
2,250
4


1,108
116
Guadeloupe
202,163

1,012

N/A
N/A
N/A
19
505,668
2,531
938,039
2,346,306
399,794
North America
2
395
0


497,509
117
El Salvador
201,785

4,230

179,410

18,145
8
30,805
646
2,610,114
398,467
6,550,389
North America
32
1,549
3


2,770
118
Trinidad and Tobago
191,257

4,385

186,827

45
8
135,973
3,117
909,477
646,585
1,406,585
North America
7
321
2


32
119
Maldives
185,894

311

163,687

21,896
25
343,621
575
2,213,831
4,092,223
540,985
Asia
3
1,740
0


40,474
120
Ghana
171,589

1,462

170,073

54
2
5,297
45
2,535,386
78,264
32,395,450
Africa
189
22,158
13


2
121
Namibia
171,222

4,090

167,099

33

65,008
1,553
1,062,663
403,460
2,633,874
Africa
15
644
2


13
122
Uganda
170,610

3,632

100,431

66,547
3
3,523
75
3,012,408
62,198
48,432,863
Africa
284
13,335
16


1,374
123
Jamaica
154,687

3,532

102,678

48,477

51,820
1,183
1,183,986
396,633
2,985,094
North America
19
845
3


16,240
124
Cambodia
138,726

3,056

135,669

1

8,080
178
3,091,420
180,062
17,168,639
Asia
124
5,618
6


0.06
125
Rwanda
133,194

1,468

131,647

79

9,793
108
6,021,981
442,778
13,600,464
Africa
102
9,265
2


6
126
Cameroon
124,834

1,970

122,640

224
13
4,472
71
1,751,774
62,762
27,911,548
Africa
224
14,168
16


8
127
Malta
118,214

833

116,744

637
4
266,228
1,876
2,129,819
4,796,533
444,033
Europe
4
533
0


1,435
128
Barbados
107,332

582

106,739

11

372,651
2,021
799,983
2,777,497
288,023
North America
3
495
0


38
129
Angola
105,353

1,934

103,396

23

3,008
55
1,499,795
42,818
35,027,343
Africa
332
18,111
23


0.7
130
Channel Islands
101,717

228

101,321

168

576,421
1,292
1,252,808
7,099,551
176,463
Europe
2
774
0


952
131
French Guiana
98,041

420

11,254

86,367
6
312,065
1,337
651,257
2,072,951
314,169
South America
3
748
0


274,906
132
DRC
95,945

1,464

84,489

9,992

1,007
15
846,704
8,890
95,240,792
Africa
993
65,055
112


105
133
Senegal
88,978

1,971

86,998

9

5,040
112
1,146,543
64,946
17,653,671
Africa
198
8,957
15


0.5
134
Malawi
88,717

2,686

85,641

390
67
4,396
133
624,784
30,959
20,180,839
Africa
227
7,513
32


19
135
Ivory Coast
88,315

834

87,473

8

3,183
30
1,687,333
60,822
27,742,298
Africa
314
33,264
16


0.3
136
Suriname
82,495

1,404

N/A
N/A
N/A

138,222
2,352
241,666
404,915
596,831
South America
7
425
2


52,502
137
New Caledonia
79,917

314

79,600

3
9
274,709
1,079
98,964
340,182
290,915
Australia/Oceania
4
926
3


10
138
French Polynesia
78,219

649

N/A
N/A
N/A
7
275,260
2,284


284,164
Australia/Oceania
4
438



155,086
139
Eswatini
74,520

1,425

73,053

42

62,896
1,203
1,048,704
885,119
1,184,817
Africa
16
831
1


35
140
Guyana
73,121

1,298

71,822

1

92,087
1,635
726,777
915,284
794,045
South America
11
612
1


1
141
Belize
70,782

688

70,085

9
6
171,722
1,669
576,016
1,397,453
412,190
North America
6
599
1


22
142
Fiji
68,918

883

67,026

1,009

75,779
971
670,477
737,221
909,466
Australia/Oceania
13
1,030
1


1,109
143
Madagascar
68,105

1,424

66,566

115

2,334
49
528,968
18,129
29,178,077
Africa
428
20,490
55


4
144
Sudan
63,922

5,034

58,626

262

1,390
109
562,941
12,240
45,992,020
Africa
720
9,136
82


6
145
Mauritania
63,715

997

62,471

247

12,998
203
1,009,957
206,030
4,901,981
Africa
77
4,917
5


50
146
Cabo Verde
63,281

413

62,786

82
23
111,473
728
401,622
707,482
567,678
Africa
9
1,375
1


144
147
Bhutan
62,650

21

61,564

1,065

79,511
27
2,303,734
2,923,739
787,941
Asia
13
37,521
0


1,352
148
Syria
57,508

3,164

54,344

0

2,970
163
146,269
7,553
19,364,809
Asia
337
6,120
132



149
Burundi
53,719

38

53,569

112

4,255
3
345,742
27,386
12,624,840
Africa
235
332,233
37


9
150
Seychelles
50,937

172

50,750

15

512,311
1,730


99,426
Africa
2
578



151
151
Gabon
48,981

306

48,674

1

21,008
131
1,621,909
695,641
2,331,533
Africa
48
7,619
1


0.4
152
Andorra
47,939

165

47,563

211
14
618,863
2,130
249,838
3,225,256
77,463
Europe
2
469
0


2,724
153
Papua New Guinea
46,837

670

43,982

2,185
7
5,040
72
249,149
26,813
9,292,169
Australia/Oceania
198
13,869
37


235
154
Curaçao
45,986

295

44,720

971
3
277,812
1,782
496,693
3,000,640
165,529
North America
4
561
0


5,866
155
Aruba
44,114

236

42,438

1,440
2
409,947
2,193
177,885
1,653,068

107,609
North America
2
456
1


13,382
156
Tanzania
42,973

846

N/A
N/A
N/A
7
679
13


63,298,550
Africa
1,473
74,821



663
157
Mayotte
42,008

188

N/A
N/A
N/A

146,748
657
176,919
618,038
286,259
Africa
7
1,523
2


135,737
158
Mauritius
41,977

1,043

40,208

726

32,930
818
358,675
281,374
1,274,727
Africa
30
1,222
4


570
159
Togo
39,470

290

39,169

11

4,547
33
810,204
93,332
8,680,837
Africa
220
29,934
11


1
160
Guinea
38,280

467

37,757

56
8
2,761
34
660,107
47,607
13,865,691
Africa
362
29,691
21


4
161
Isle of Man
38,008

116

N/A
N/A
N/A

443,335
1,353
150,753
1,758,422
85,732
Europe
2
739
1


129,450
162
Bahamas
37,491

833

36,366

292
1
93,607
2,080
257,839
643,767
400,516
North America
11
481
2


729
163
Lesotho
34,790

723

25,980

8,087

15,990
332
431,221
198,199
2,175,699
Africa
63
3,009
5


3,717
164
Faeroe Islands
34,658

28

N/A
N/A
N/A
5
703,959
569
778,000
15,802,409
49,233
Europe
1
1,758
0


547,133
165
Haiti
34,218

860

33,216

142

2,930
74
132,422
11,337
11,680,283
North America
341
13,582
88


12
166
Mali
33,134

743

32,312

79

1,543
35
802,511
37,372
21,473,764
Africa
648
28,901
27


4
167
Cayman Islands
31,472

37

8,553

22,882
1
467,797
550
222,773
3,311,280
67,277
North America
2
1,818
0


340,116
168
Saint Lucia
30,028

409

29,095

524

162,214
2,209
210,983
1,139,752
185,113
North America
6
453
1


2,831
169
Benin
28,014

163

27,847

4

2,191
13
604,310
47,268
12,784,726
Africa
456
78,434
21


0.3
170
Somalia
27,334

1,361

13,182

12,791

1,623
81
400,466
23,778
16,841,795
Africa
616
12,375
42


759
171
Micronesia
25,929

65

N/A
N/A
N/A
1
220,693
553
80,318
683,621
117,489
Australia/Oceania
5
1,808
1


157,010
172
Congo
25,375

386

24,006

983

4,377
67
347,815
59,991
5,797,805
Africa
228
15,020
17


170
173
Solomon Islands
24,575

153

N/A
N/A
N/A
1
34,077
212


721,159
Australia/Oceania
29
4,713



11,183
174
San Marino
23,873

123

23,721

29
4
700,396
3,609
196,855
5,775,414
34,085
Europe
1
277
0


851
175
Timor-Leste
23,423

138

23,102

183

17,104
101
278,529
203,391
1,369,429
Asia
58
9,923
5


134
176
Burkina Faso
22,056

396

21,596

64

998
18
248,995
11,265
22,102,838
Africa
1,002
55,815
89


3
177
Liechtenstein
21,437

91

21,345

1

558,444
2,371
112,457
2,929,559
38,387
Europe
2
422
0


26
178
Gibraltar
20,550

113

16,579

3,858

609,720
3,353
534,283
15,852,213
33,704
Europe
2
298
0


114,467
179
Grenada
19,683

238

19,358

87
4
173,457
2,097
182,981
1,612,523
113,475
North America
6
477
1


767
180
Bermuda
18,860

165

18,685

10

304,493
2,664
1,029,558
16,622,128
61,939
North America
3
375
0


161
181
Nicaragua
18,491

225

4,225

14,041

2,728
33


6,779,100
North America
367
30,129



2,071
182
South Sudan
18,368

138

18,115

115
1
1,581
12
410,280
35,313
11,618,511
Africa
633
84,192
28


10
183
Tajikistan
17,786

125

17,264

397

1,786
13


9,957,464
Asia
560
79,660



40
184
Equatorial Guinea
17,229

183

16,907

139
5
11,512
122
365,697
244,342
1,496,662
Africa
87
8,178
4


93
185
Tonga
16,814

13

15,638

1,163

156,048
121
535,009
4,965,327
107,749
Australia/Oceania
6
8,288
0


10,794
186
Samoa
16,737

31

1,605

15,101

82,759
153
187,397
926,612
202,239
Australia/Oceania
12
6,524
1


74,669
187
Monaco
16,178

67

15,992

119
4
406,656
1,684
78,646
1,976,875
39,783
Europe
2
594
1


2,991
188
Marshall Islands
16,081

17

15,954

110

267,762
283


60,057
Australia/Oceania
4
3,533



1,832
189
Dominica
15,760

74

15,673

13

217,848
1,023
229,344
3,170,187
72,344
North America
5
978
0


180
190
Djibouti
15,690

189

15,427

74

15,441
186
305,941
301,094
1,016,097
Africa
65
5,376
3


73
191
CAR
15,368

113

15,200

55
2
3,063
23
81,294
16,205
5,016,678
Africa
326
44,395
62


11
192
Gambia
12,626

372

12,189

65

4,935
145
155,686
60,851
2,558,482
Africa
203
6,878
16


25
193
Saint Martin
12,280

63

1,399

10,818
7
309,086
1,586
112,382
2,828,643
39,730
North America
3
631
0


272,288
194
Vanuatu
12,014

14

11,976

24

37,330
44
24,976
77,606
321,832
Australia/Oceania
27
22,988
13


75
195
Greenland
11,971

21

2,761

9,189
4
210,117
369
164,926
2,894,810
56,973
North America
5
2,713
0


161,287
196
Yemen
11,945

2,159

9,124

662
23
383
69
329,592
10,579
31,154,867
Asia
2,608
14,430
95


21
197
Caribbean Netherlands
11,682

38

10,476

1,168

438,398
1,426
30,126
1,130,559
26,647
North America
2
701
1


43,832
198
Sint Maarten
11,030

92

10,905

33
N/A
250,876
2,093
62,056
1,411,454
43,966
North America
4
478
1


751
199
Eritrea
10,189

103

10,086

0

2,782
28
23,693
6,470
3,662,244
Africa
359
35,556
155



200
Niger
9,931

312

8,890

729
1
381
12
254,538
9,759
26,083,660
Africa
2,626
83,601
102


28
201
St. Vincent Grenadines
9,601

124

9,472

5

86,068
1,112
113,886
1,020,932
111,551
North America
12
900
1


45
202
Guinea-Bissau
9,350

176

8,929

245
6
4,531
85
145,231
70,385
2,063,367
Africa
221
11,724
14


119
203
Antigua and Barbuda
9,106

146

8,954

6
1
91,509
1,467
18,901
189,943
99,509
North America
11
682
5


60
204
Comoros
9,093

161

8,885

47

10,021
177


907,419
Africa
100
5,636



52
205
Liberia
8,090

295

7,783

12
2
1,525
56
139,824
26,356
5,305,117
Africa
656
17,983
38


2
206
Sierra Leone
7,762

126

N/A
N/A
N/A

934
15
259,958
31,296
8,306,436
Africa
1,070
65,924
32


330
207
Chad
7,696

194

4,874

2,628

442
11
191,341
10,988
17,413,580
Africa
2,263
89,761
91


151
208
British Virgin Islands
7,305

64

N/A
N/A
N/A

238,757
2,092
107,339
3,508,269
30,596
North America
4
478
0


392
209
Cook Islands
7,050

2

7,038

10

401,229
114
19,690
1,120,596
17,571
Australia/Oceania
2
8,786
1


569
210
Saint Kitts and Nevis
6,598

48

6,550

0

122,478
891
126,939
2,356,351
53,871
North America
8
1,122
0



211
Turks and Caicos
6,565

38

6,509

18
4
165,195
956
612,335
15,408,143
39,741
North America
6
1,046
0


453
212
Sao Tome and Principe
6,542

80

6,422

40

28,733
351
29,036
127,530
227,679
Africa
35
2,846
8


176
213
Palau
5,999

9

5,989

1

329,019
494
69,532
3,813,525
18,233
Australia/Oceania
3
2,026
0


55
214
St. Barth
5,478

6

N/A
N/A
N/A

550,830
603
78,646
7,908,095
9,945
North America
2
1,658
0


503,771
215
Nauru
5,393

1

5,347

45

494,635
92
20,509
1,881,042
10,903
Australia/Oceania
2
10,903
1


4,127
216
Kiribati
5,014

18

2,703

2,293
3
40,626
146


123,419
Australia/Oceania
25
6,857



18,579
217
Anguilla
3,904

12

3,879

13
4
256,336
788
51,382
3,373,736
15,230
North America
4
1,269
0


854
218
Macao
3,515

121

3,393

1

5,266
181
7,850
11,760
667,490
Asia
190
5,516
85


1
219
Saint Pierre Miquelon
3,452

2

2,449

1,001
1
599,410
347
25,400
4,410,488
5,759
North America
2
2,880
0


173,815
220
Wallis and Futuna
3,427

7

438

2,982

312,056
637
20,508
1,867,419
10,982
Australia/Oceania
3
1,569
1


271,535
221
Tuvalu
2,805





2,805

232,471



12,066
Australia/Oceania
4




232,471
222
Saint Helena
2,166



2

2,164

354,211



6,115
Africa
3




353,884
223
Falkland Islands
1,930



1,930

0

545,352

8,632
2,439,107
3,539
South America
2

0



224
Montserrat
1,403

8

1,376

19

282,578
1,611
17,762
3,577,442
4,965
North America
4
621
0


3,827
225
Niue
800



798

2

493,218



1,622
Australia/Oceania
2




1,233
226
Diamond Princess
712

13

699

0













227
Vatican City
29



29

0

36,295



799
Europe
28





228
Western Sahara
10

1

9

0

16
2


626,161
Africa
62,616
626,161




229
MS Zaandam
9

2

7

0













230
Tokelau
5





5

3,628



1,378
Australia/Oceania
276




3,628
231
China
503,302

5,272

379,053

118,977
N/A
347
4
160,000,000
110,461
1,448,471,400
Asia
2,878
274,748
9


82

In [11]:
all_data = []
for i in range(8,len(table_rows)):
    td = table_rows[i].find_all('td')
    
    country_data = []
    for table_data in td:
        country_data.append(table_data.text)
    all_data.append(country_data)

In [12]:
all_data

[['1',
  'USA',
  '106,464,679',
  '',
  '1,158,158                                ',
  '',
  '104,311,698',
  '',
  '994,823',
  '1,636',
  '317,990',
  '3,459',
  '1,175,946,071',
  '3,512,328',
  '334,805,269 ',
  'North America',
  '3',
  '289',
  '0',
  '',
  '',
  '2,971'],
 ['2',
  'India',
  '44,808,022',
  '',
  '531,091                                ',
  '',
  '44,223,211',
  '',
  '53,720',
  'N/A',
  '31,855',
  '378',
  '923,497,482',
  '656,531',
  '1,406,631,776 ',
  'Asia',
  '31',
  '2,649',
  '2',
  '',
  '',
  '38'],
 ['3',
  'France',
  '39,896,203',
  '',
  '166,024                                ',
  '',
  '39,592,740',
  '',
  '137,439',
  '869',
  '608,317',
  '2,531',
  '271,490,188',
  '4,139,547',
  '65,584,518 ',
  'Europe',
  '2',
  '395',
  '0',
  '',
  '',
  '2,096'],
 ['4',
  'Germany',
  '38,382,386',
  '',
  '171,992                                ',
  '',
  '38,149,200',
  '',
  '61,194',
  'N/A',
  '457,567',
  '2,050',
  '122,332,384',
  '1,458,359',
  '83,883,596 ',
  'Europe',
  '2',
  '488',
  '1',
  '',
  '',
  '730'],
 ['5',
  'Brazil',
  '37,358,092',
  '',
  '700,811                                ',
  '',
  '36,249,161',
  '',
  '408,120',
  'N/A',
  '173,473',
  '3,254',
  '63,776,166',
  '296,146',
  '215,353,593 ',
  'South America',
  '6',
  '307',
  '3',
  '',
  '',
  '1,895'],
 ['6',
  'Japan',
  '33,573,695',
  '',
  '74,220                                ',
  '',
  '21,725,273',
  '',
  '11,774,202',
  '53',
  '267,339',
  '591',
  '99,119,701',
  '789,265',
  '125,584,838 ',
  'Asia',
  '4',
  '1,692',
  '1',
  '',
  '',
  '93,755'],
 ['7',
  'S. Korea',
  '30,978,954',
  '',
  '34,368                                ',
  '',
  '30,764,355',
  '+13,132',
  '180,231',
  '114',
  '603,526',
  '670',
  '15,804,065',
  '307,892',
  '51,329,899 ',
  'Asia',
  '2',
  '1,494',
  '3',
  '',
  '',
  '3,511'],
 ['8',
  'Italy',
  '25,737,170',
  '',
  '189,391                                ',
  '',
  '25,413,901',
  '',
  '133,878',
  '83',
  '427,082',
  '3,143',
  '270,717,229',
  '4,492,280',
  '60,262,770 ',
  'Europe',
  '2',
  '318',
  '0',
  '',
  '',
  '2,222'],
 ['9',
  'UK',
  '24,448,729',
  '',
  '209,396                                ',
  '',
  '24,239,333',
  '',
  '0',
  'N/A',
  '356,927',
  '3,057',
  '522,526,476',
  '7,628,357',
  '68,497,907 ',
  'Europe',
  '3',
  '327',
  '0',
  '',
  '',
  ''],
 ['10',
  'Russia',
  '22,758,243',
  '',
  '397,790                                ',
  '',
  '22,144,313',
  '',
  '216,140',
  'N/A',
  '156,086',
  '2,728',
  '273,400,000',
  '1,875,095',
  '145,805,947 ',
  'Europe',
  '6',
  '367',
  '1',
  '',
  '',
  '1,482'],
 ['11',
  'Turkey',
  '17,232,066',
  '',
  '102,174                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '',
  '201,399',
  '1,194',
  '162,743,369',
  '1,902,052',
  '85,561,976 ',
  'Asia',
  '5',
  '837',
  '1',
  '',
  '',
  '4,024'],
 ['12',
  'Spain',
  '13,813,830',
  '',
  '120,606                                ',
  '',
  '13,659,874',
  '',
  '33,350',
  '231',
  '295,678',
  '2,582',
  '471,036,328',
  '10,082,298',
  '46,719,142 ',
  'Europe',
  '3',
  '387',
  '0',
  '',
  '',
  '714'],
 ['13',
  'Vietnam',
  '11,530,356',
  '',
  '43,186                                ',
  '',
  '10,615,343',
  '',
  '871,827',
  '10',
  '116,523',
  '436',
  '85,826,548',
  '867,342',
  '98,953,541 ',
  'Asia',
  '9',
  '2,291',
  '1',
  '',
  '',
  '8,810'],
 ['14',
  'Australia',
  '11,381,793',
  '',
  '20,049                                ',
  '',
  '11,314,115',
  '',
  '47,629',
  '43',
  '436,606',
  '769',
  '78,835,048',
  '3,024,116',
  '26,068,792 ',
  'Australia/Oceania',
  '2',
  '1,300',
  '0',
  '',
  '',
  '1,827'],
 ['15',
  'Taiwan',
  '10,239,998',
  '',
  '19,005                                ',
  '',
  '10,220,993',
  '+4',
  '0',
  '',
  '428,656',
  '796',
  '30,742,304',
  '1,286,903',
  '23,888,595 ',
  'Asia',
  '2',
  '1,257',
  '1',
  '',
  '',
  ''],
 ['16',
  'Argentina',
  '10,044,957',
  '',
  '130,472                                ',
  '',
  '9,914,485',
  '',
  '0',
  '363',
  '218,320',
  '2,836',
  '35,716,069',
  '776,264',
  '46,010,234 ',
  'South America',
  '5',
  '353',
  '1',
  '',
  '',
  ''],
 ['17',
  'Netherlands',
  '8,610,372',
  '',
  '22,992                                ',
  '',
  '8,582,526',
  '+437',
  '4,854',
  '53',
  '500,270',
  '1,336',
  '25,984,435',
  '1,509,718',
  '17,211,447 ',
  'Europe',
  '2',
  '749',
  '1',
  '',
  '',
  '282'],
 ['18',
  'Iran',
  '7,597,982',
  '',
  '145,571                                ',
  '',
  '7,342,490',
  '',
  '109,921',
  '407',
  '88,325',
  '1,692',
  '55,353,767',
  '643,478',
  '86,022,837 ',
  'Asia',
  '11',
  '591',
  '2',
  '',
  '',
  '1,278'],
 ['19',
  'Mexico',
  '7,563,576',
  '',
  '333,669                                ',
  '',
  '6,809,445',
  '',
  '420,462',
  'N/A',
  '57,490',
  '2,536',
  '19,835,770',
  '150,770',
  '131,562,772 ',
  'North America',
  '17',
  '394',
  '7',
  '',
  '',
  '3,196'],
 ['20',
  'Indonesia',
  '6,756,541',
  '',
  '161,116                                ',
  '',
  '6,586,736',
  '',
  '8,689',
  'N/A',
  '24,205',
  '577',
  '114,158,919',
  '408,975',
  '279,134,505 ',
  'Asia',
  '41',
  '1,733',
  '2',
  '',
  '',
  '31'],
 ['21',
  'Poland',
  '6,508,636',
  '',
  '119,480                                ',
  '',
  '5,335,940',
  '',
  '1,053,216',
  '696',
  '172,461',
  '3,166',
  '38,606,044',
  '1,022,953',
  '37,739,785 ',
  'Europe',
  '6',
  '316',
  '1',
  '',
  '',
  '27,907'],
 ['22',
  'Colombia',
  '6,363,544',
  '',
  '142,698                                ',
  '',
  '6,186,501',
  '',
  '34,345',
  '342',
  '123,533',
  '2,770',
  '36,951,507',
  '717,327',
  '51,512,762 ',
  'South America',
  '8',
  '361',
  '1',
  '',
  '',
  '667'],
 ['23',
  'Austria',
  '6,052,650',
  '',
  '22,276                                ',
  '',
  '6,016,085',
  '',
  '14,289',
  '55',
  '667,569',
  '2,457',
  '211,273,524',
  '23,302,116',
  '9,066,710 ',
  'Europe',
  '1',
  '407',
  '0',
  '',
  '',
  '1,576'],
 ['24',
  'Greece',
  '5,972,760',
  '',
  '36,629                                ',
  '',
  '5,927,050',
  '+1,965',
  '9,081',
  '115',
  '578,944',
  '3,550',
  '102,228,365',
  '9,909,078',
  '10,316,637 ',
  'Europe',
  '2',
  '282',
  '0',
  '',
  '',
  '880'],
 ['25',
  'Portugal',
  '5,577,825',
  '',
  '26,480                                ',
  '',
  '5,545,402',
  '',
  '5,943',
  '61',
  '550,050',
  '2,611',
  '46,065,483',
  '4,542,692',
  '10,140,570 ',
  'Europe',
  '2',
  '383',
  '0',
  '',
  '',
  '586'],
 ['26',
  'Ukraine',
  '5,484,936',
  '',
  '111,789                                ',
  '',
  '5,334,190',
  '',
  '38,957',
  '',
  '126,989',
  '2,588',
  '32,603,805',
  '754,855',
  '43,192,122 ',
  'Europe',
  '8',
  '386',
  '1',
  '',
  '',
  '902'],
 ['27',
  'Chile',
  '5,278,252',
  '',
  '64,497                                ',
  '',
  '5,211,301',
  '',
  '2,454',
  '69',
  '274,192',
  '3,350',
  '49,226,745',
  '2,557,208',
  '19,250,195 ',
  'South America',
  '4',
  '298',
  '0',
  '',
  '',
  '127'],
 ['28',
  'Malaysia',
  '5,056,911',
  '',
  '36,994                                ',
  '',
  '5,006,634',
  '',
  '13,283',
  '10',
  '152,403',
  '1,115',
  '68,342,991',
  '2,059,698',
  '33,181,072 ',
  'Asia',
  '7',
  '897',
  '0',
  '',
  '',
  '400'],
 ['29',
  'Israel',
  '4,818,346',
  '',
  '12,416                                ',
  '',
  '4,798,473',
  '',
  '7,457',
  '21',
  '516,657',
  '1,331',
  '41,373,364',
  '4,436,346',
  '9,326,000 ',
  'Asia',
  '2',
  '751',
  '0',
  '',
  '',
  '800'],
 ['30',
  'Belgium',
  '4,786,803',
  '',
  '34,166                                ',
  '',
  '4,723,282',
  '',
  '29,355',
  '43',
  '410,241',
  '2,928',
  '36,973,399',
  '3,168,711',
  '11,668,278 ',
  'Europe',
  '2',
  '342',
  '0',
  '',
  '',
  '2,516'],
 ['31',
  'DPRK',
  '4,772,813',
  '',
  '74                                ',
  '',
  '4,772,739',
  '',
  '0',
  '',
  '183,636',
  '3',
  '',
  '',
  '25,990,679 ',
  'Asia',
  '5',
  '351,225',
  '',
  '',
  '',
  ''],
 ['32',
  'Thailand',
  '4,728,967',
  '',
  '33,940                                ',
  '',
  '4,692,636',
  '',
  '2,391',
  'N/A',
  '67,481',
  '484',
  '17,270,775',
  '246,450',
  '70,078,203 ',
  'Asia',
  '15',
  '2,065',
  '4',
  '',
  '',
  '34'],
 ['33',
  'Canada',
  '4,641,301',
  '',
  '52,247                                ',
  '',
  '4,563,303',
  '+1,255',
  '25,751',
  '99',
  '120,904',
  '1,361',
  '66,343,123',
  '1,728,207',
  '38,388,419 ',
  'North America',
  '8',
  '735',
  '1',
  '',
  '',
  '671'],
 ['34',
  'Czechia',
  '4,637,897',
  '',
  '42,726                                ',
  '',
  '4,591,159',
  '',
  '4,012',
  '23',
  '431,963',
  '3,979',
  '57,149,297',
  '5,322,757',
  '10,736,784 ',
  'Europe',
  '2',
  '251',
  '0',
  '',
  '',
  '374'],
 ['35',
  'Peru',
  '4,496,896',
  '',
  '219,991                                ',
  '',
  '4,273,686',
  '+327',
  '3,219',
  '33',
  '133,502',
  '6,531',
  '38,423,871',
  '1,140,709',
  '33,684,208 ',
  'South America',
  '7',
  '153',
  '1',
  '',
  '',
  '96'],
 ['36',
  'Switzerland',
  '4,400,218',
  '',
  '14,452                                ',
  '',
  '4,379,844',
  '',
  '5,922',
  '39',
  '501,527',
  '1,647',
  '23,833,472',
  '2,716,487',
  '8,773,637 ',
  'Europe',
  '2',
  '607',
  '0',
  '',
  '',
  '675'],
 ['37',
  'Philippines',
  '4,085,539',
  '',
  '66,437                                ',
  '',
  '4,009,622',
  '',
  '9,480',
  '162',
  '36,313',
  '591',
  '34,914,751',
  '310,329',
  '112,508,994 ',
  'Asia',
  '28',
  '1,693',
  '3',
  '',
  '',
  '84'],
 ['38',
  'South Africa',
  '4,075,849',
  '',
  '102,595                                ',
  '',
  '3,912,506',
  '',
  '60,748',
  '192',
  '67,085',
  '1,689',
  '26,795,090',
  '441,027',
  '60,756,135 ',
  'Africa',
  '15',
  '592',
  '2',
  '',
  '',
  '1,000'],
 ['39',
  'Romania',
  '3,380,891',
  '',
  '67,961                                ',
  '',
  '3,299,960',
  '',
  '12,970',
  '132',
  '177,649',
  '3,571',
  '27,131,523',
  '1,425,624',
  '19,031,335 ',
  'Europe',
  '6',
  '280',
  '1',
  '',
  '',
  '682'],
 ['40',
  'Denmark',
  '3,179,563',
  '',
  '8,464                                ',
  '',
  '3,169,944',
  '',
  '1,155',
  '19',
  '544,917',
  '1,451',
  '129,253,612',
  '22,151,623',
  '5,834,950 ',
  'Europe',
  '2',
  '689',
  '0',
  '',
  '',
  '198'],
 ['41',
  'Hong Kong',
  '2,886,633',
  '',
  '13,490                                ',
  '',
  '2,870,397',
  '',
  '2,746',
  '28',
  '379,605',
  '1,774',
  '76,127,725',
  '10,011,143',
  '7,604,299 ',
  'Asia',
  '3',
  '564',
  '0',
  '',
  '',
  '361'],
 ['42',
  'Sweden',
  '2,703,773',
  '',
  '23,928                                ',
  '',
  '2,676,426',
  '+114',
  '3,419',
  '8',
  '264,584',
  '2,342',
  '19,500,873',
  '1,908,301',
  '10,218,971 ',
  'Europe',
  '4',
  '427',
  '1',
  '',
  '',
  '335'],
 ['43',
  'Serbia',
  '2,527,640',
  '',
  '18,002                                ',
  '',
  '2,498,044',
  '',
  '11,594',
  '13',
  '292,111',
  '2,080',
  '12,708,633',
  '1,468,694',
  '8,653,016 ',
  'Europe',
  '3',
  '481',
  '1',
  '',
  '',
  '1,340'],
 ['44',
  'Iraq',
  '2,465,545',
  '',
  '25,375                                ',
  '',
  '2,439,497',
  '',
  '673',
  '21',
  '58,474',
  '602',
  '19,544,451',
  '463,523',
  '42,164,965 ',
  'Asia',
  '17',
  '1,662',
  '2',
  '',
  '',
  '16'],
 ['45',
  'Singapore',
  '2,314,707',
  '',
  '1,727                                ',
  '',
  '2,149,583',
  '',
  '163,397',
  '2',
  '389,449',
  '291',
  '24,756,666',
  '4,165,302',
  '5,943,546 ',
  'Asia',
  '3',
  '3,442',
  '0',
  '',
  '',
  '27,492'],
 ['46',
  'New Zealand',
  '2,286,481',
  '',
  '4,045                                ',
  '',
  '2,271,682',
  '',
  '10,754',
  '',
  '466,800',
  '826',
  '7,768,604',
  '1,586,011',
  '4,898,203 ',
  'Australia/Oceania',
  '2',
  '1,211',
  '1',
  '',
  '',
  '2,195'],
 ['47',
  'Hungary',
  '2,200,211',
  '',
  '48,828                                ',
  '',
  '2,147,103',
  '',
  '4,280',
  '2',
  '229,039',
  '5,083',
  '11,394,556',
  '1,186,160',
  '9,606,259 ',
  'Europe',
  '4',
  '197',
  '1',
  '',
  '',
  '446'],
 ['48',
  'Bangladesh',
  '2,038,091',
  '',
  '29,446                                ',
  '',
  '1,998,448',
  '',
  '10,197',
  'N/A',
  '12,140',
  '175',
  '15,254,399',
  '90,862',
  '167,885,689 ',
  'Asia',
  '82',
  '5,701',
  '11',
  '',
  '',
  '61'],
 ['49',
  'Slovakia',
  '1,866,064',
  '',
  '21,141                                ',
  '',
  '1,844,330',
  '',
  '593',
  '23',
  '341,758',
  '3,872',
  '7,422,919',
  '1,359,461',
  '5,460,193 ',
  'Europe',
  '3',
  '258',
  '1',
  '',
  '',
  '109'],
 ['50',
  'Georgia',
  '1,836,791',
  '',
  '17,032                                ',
  '',
  '1,776,548',
  '',
  '43,211',
  '',
  '462,815',
  '4,292',
  '16,920,079',
  '4,263,340',
  '3,968,738 ',
  'Asia',
  '2',
  '233',
  '0',
  '',
  '',
  '10,888'],
 ['51',
  'Jordan',
  '1,746,997',
  '',
  '14,122                                ',
  '',
  '1,731,007',
  '',
  '1,868',
  '59',
  '169,597',
  '1,371',
  '17,201,885',
  '1,669,945',
  '10,300,869 ',
  'Asia',
  '6',
  '729',
  '1',
  '',
  '',
  '181'],
 ['52',
  'Ireland',
  '1,708,933',
  '',
  '8,810                                ',
  '',
  '1,696,485',
  '',
  '3,638',
  '19',
  '340,411',
  '1,755',
  '13,083,449',
  '2,606,161',
  '5,020,199 ',
  'Europe',
  '3',
  '570',
  '0',
  '',
  '',
  '725'],
 ['53',
  'Pakistan',
  '1,580,429',
  '+20',
  '30,655                                ',
  '',
  '1,538,689',
  '',
  '11,085',
  '15',
  '6,887',
  '134',
  '30,570,862',
  '133,213',
  '229,488,994 ',
  'Asia',
  '145',
  '7,486',
  '8',
  '0.09',
  '',
  '48'],
 ['54',
  'Norway',
  '1,482,235',
  '',
  '5,213                                ',
  '',
  '1,475,779',
  '',
  '1,243',
  '20',
  '268,941',
  '946',
  '11,002,430',
  '1,996,315',
  '5,511,370 ',
  'Europe',
  '4',
  '1,057',
  '1',
  '',
  '',
  '226'],
 ['55',
  'Finland',
  '1,469,865',
  '',
  '9,144                                ',
  '',
  '1,456,454',
  '+210',
  '4,267',
  '21',
  '264,604',
  '1,646',
  '12,069,254',
  '2,172,699',
  '5,554,960 ',
  'Europe',
  '4',
  '607',
  '0',
  '',
  '',
  '768'],
 ['56',
  'Kazakhstan',
  '1,410,791',
  '',
  '13,848                                ',
  '',
  '1,383,020',
  '',
  '13,923',
  '24',
  '73,459',
  '721',
  '11,575,012',
  '602,707',
  '19,205,043 ',
  'Asia',
  '14',
  '1,387',
  '2',
  '',
  '',
  '725'],
 ['57',
  'Slovenia',
  '1,342,491',
  '',
  '7,100                                ',
  '',
  '1,328,006',
  '',
  '7,385',
  '8',
  '646,039',
  '3,417',
  '2,847,701',
  '1,370,382',
  '2,078,034 ',
  'Europe',
  '2',
  '293',
  '1',
  '',
  '',
  '3,554'],
 ['58',
  'Lithuania',
  '1,316,799',
  '',
  '9,650                                ',
  '',
  '1,303,244',
  '',
  '3,905',
  '7',
  '494,720',
  '3,625',
  '10,425,065',
  '3,916,682',
  '2,661,708 ',
  'Europe',
  '2',
  '276',
  '0',
  '',
  '',
  '1,467'],
 ['59',
  'Bulgaria',
  '1,302,146',
  '',
  '38,288                                ',
  '',
  '1,260,996',
  '',
  '2,862',
  '40',
  '190,244',
  '5,594',
  '11,151,672',
  '1,629,266',
  '6,844,597 ',
  'Europe',
  '5',
  '179',
  '1',
  '',
  '',
  '418'],
 ['60',
  'Morocco',
  '1,272,733',
  '',
  '16,296                                ',
  '',
  '1,256,151',
  '',
  '286',
  '3',
  '33,694',
  '431',
  '13,001,033',
  '344,191',
  '37,772,756 ',
  'Africa',
  '30',
  '2,318',
  '3',
  '',
  '',
  '8'],
 ['61',
  'Croatia',
  '1,271,276',
  '',
  '18,091                                ',
  '',
  '1,252,694',
  '',
  '491',
  '4',
  '313,177',
  '4,457',
  '5,560,149',
  '1,369,736',
  '4,059,286 ',
  'Europe',
  '3',
  '224',
  '1',
  '',
  '',
  '121'],
 ['62',
  'Guatemala',
  '1,246,722',
  '',
  '20,189                                ',
  '',
  '1,225,638',
  '',
  '895',
  '5',
  '67,086',
  '1,086',
  '7,148,360',
  '384,651',
  '18,584,039 ',
  'North America',
  '15',
  '921',
  '3',
  '',
  '',
  '48'],
 ['63',
  'Lebanon',
  '1,235,804',
  '',
  '10,885                                ',
  '',
  '1,087,587',
  '',
  '137,332',
  '74',
  '184,866',
  '1,628',
  '4,795,578',
  '717,380',
  '6,684,849 ',
  'Asia',
  '5',
  '614',
  '1',
  '',
  '',
  '20,544'],
 ['64',
  'Costa Rica',
  '1,226,315',
  '',
  '9,326                                ',
  '',
  '860,711',
  '',
  '356,278',
  '52',
  '236,633',
  '1,800',
  '4,659,757',
  '899,158',
  '5,182,354 ',
  'North America',
  '4',
  '556',
  '1',
  '',
  '',
  '68,748'],
 ['65',
  'Bolivia',
  '1,196,464',
  '',
  '22,375                                ',
  '',
  '1,165,163',
  '',
  '8,926',
  '220',
  '99,766',
  '1,866',
  '2,705,422',
  '225,590',
  '11,992,656 ',
  'South America',
  '10',
  '536',
  '4',
  '',
  '',
  '744'],
 ['66',
  'Tunisia',
  '1,152,262',
  '',
  '29,367                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '44',
  '95,650',
  '2,438',
  '5,008,040',
  '415,720',
  '12,046,656 ',
  'Africa',
  '10',
  '410',
  '2',
  '',
  '',
  '1,070'],
 ['67',
  'Cuba',
  '1,112,990',
  '',
  '8,530                                ',
  '',
  '1,104,340',
  '',
  '120',
  '2',
  '98,445',
  '754',
  '14,324,663',
  '1,267,036',
  '11,305,652 ',
  'North America',
  '10',
  '1,325',
  '1',
  '',
  '',
  '11'],
 ['68',
  'UAE',
  '1,060,146',
  '',
  '2,349                                ',
  '',
  '1,041,294',
  '',
  '16,503',
  '',
  '105,155',
  '233',
  '200,056,552',
  '19,843,366',
  '10,081,785 ',
  'Asia',
  '10',
  '4,292',
  '0',
  '',
  '',
  '1,637'],
 ['69',
  'Ecuador',
  '1,059,529',
  '',
  '36,017                                ',
  '',
  '1,022,992',
  '',
  '520',
  '759',
  '58,494',
  '1,988',
  '3,082,403',
  '170,173',
  '18,113,361 ',
  'South America',
  '17',
  '503',
  '6',
  '',
  '',
  '29'],
 ['70',
  'Uruguay',
  '1,037,095',
  '',
  '7,621                                ',
  '',
  '1,028,996',
  '',
  '478',
  '18',
  '296,651',
  '2,180',
  '6,114,822',
  '1,749,083',
  '3,496,016 ',
  'South America',
  '3',
  '459',
  '1',
  '',
  '',
  '137'],
 ['71',
  'Panama',
  '1,035,357',
  '',
  '8,617                                ',
  '',
  '1,026,192',
  '',
  '548',
  '16',
  '232,823',
  '1,938',
  '7,621,296',
  '1,713,820',
  '4,446,964 ',
  'North America',
  '4',
  '516',
  '1',
  '',
  '',
  '123'],
 ['72',
  'Mongolia',
  '1,007,943',
  '',
  '2,179                                ',
  '',
  '1,005,732',
  '',
  '32',
  '192',
  '298,378',
  '645',
  '4,030,048',
  '1,193,000',
  '3,378,078 ',
  'Asia',
  '3',
  '1,550',
  '1',
  '',
  '',
  '9'],
 ['73',
  'Nepal',
  '1,002,128',
  '',
  '12,022                                ',
  '',
  '989,729',
  '',
  '377',
  '',
  '33,155',
  '398',
  '6,026,236',
  '199,375',
  '30,225,582 ',
  'Asia',
  '30',
  '2,514',
  '5',
  '',
  '',
  '12'],
 ['74',
  'Belarus',
  '994,037',
  '',
  '7,118                                ',
  '',
  '985,592',
  '',
  '1,327',
  '',
  '105,381',
  '755',
  '13,646,641',
  '1,446,722',
  '9,432,800 ',
  'Europe',
  '9',
  '1,325',
  '1',
  '',
  '',
  '141'],
 ['75',
  'Latvia',
  '977,282',
  '',
  '6,302                                ',
  '',
  '970,544',
  '',
  '436',
  '13',
  '528,593',
  '3,409',
  '7,871,447',
  '4,257,513',
  '1,848,837 ',
  'Europe',
  '2',
  '293',
  '0',
  '',
  '',
  '236'],
 ['76',
  'Saudi Arabia',
  '838,246',
  '',
  '9,637                                ',
  '',
  '823,911',
  '',
  '4,698',
  '90',
  '23,385',
  '269',
  '45,378,829',
  '1,265,977',
  '35,844,909 ',
  'Asia',
  '43',
  '3,720',
  '1',
  '',
  '',
  '131'],
 ['77',
  'Azerbaijan',
  '830,780',
  '',

In [13]:
data = list(map(lambda x: x[1:7], all_data))

In [14]:
data

[['USA',
  '106,464,679',
  '',
  '1,158,158                                ',
  '',
  '104,311,698'],
 ['India',
  '44,808,022',
  '',
  '531,091                                ',
  '',
  '44,223,211'],
 ['France',
  '39,896,203',
  '',
  '166,024                                ',
  '',
  '39,592,740'],
 ['Germany',
  '38,382,386',
  '',
  '171,992                                ',
  '',
  '38,149,200'],
 ['Brazil',
  '37,358,092',
  '',
  '700,811                                ',
  '',
  '36,249,161'],
 ['Japan',
  '33,573,695',
  '',
  '74,220                                ',
  '',
  '21,725,273'],
 ['S. Korea',
  '30,978,954',
  '',
  '34,368                                ',
  '',
  '30,764,355'],
 ['Italy',
  '25,737,170',
  '',
  '189,391                                ',
  '',
  '25,413,901'],
 ['UK',
  '24,448,729',
  '',
  '209,396                                ',
  '',
  '24,239,333'],
 ['Russia',
  '22,758,243',
  '',
  '397,790                                ',
  '',
  '22,144,313'],
 ['Turkey',
  '17,232,066',
  '',
  '102,174                                ',
  '',
  'N/A'],
 ['Spain',
  '13,813,830',
  '',
  '120,606                                ',
  '',
  '13,659,874'],
 ['Vietnam',
  '11,530,356',
  '',
  '43,186                                ',
  '',
  '10,615,343'],
 ['Australia',
  '11,381,793',
  '',
  '20,049                                ',
  '',
  '11,314,115'],
 ['Taiwan',
  '10,239,998',
  '',
  '19,005                                ',
  '',
  '10,220,993'],
 ['Argentina',
  '10,044,957',
  '',
  '130,472                                ',
  '',
  '9,914,485'],
 ['Netherlands',
  '8,610,372',
  '',
  '22,992                                ',
  '',
  '8,582,526'],
 ['Iran',
  '7,597,982',
  '',
  '145,571                                ',
  '',
  '7,342,490'],
 ['Mexico',
  '7,563,576',
  '',
  '333,669                                ',
  '',
  '6,809,445'],
 ['Indonesia',
  '6,756,541',
  '',
  '161,116                                ',
  '',
  '6,586,736'],
 ['Poland',
  '6,508,636',
  '',
  '119,480                                ',
  '',
  '5,335,940'],
 ['Colombia',
  '6,363,544',
  '',
  '142,698                                ',
  '',
  '6,186,501'],
 ['Austria',
  '6,052,650',
  '',
  '22,276                                ',
  '',
  '6,016,085'],
 ['Greece',
  '5,972,760',
  '',
  '36,629                                ',
  '',
  '5,927,050'],
 ['Portugal',
  '5,577,825',
  '',
  '26,480                                ',
  '',
  '5,545,402'],
 ['Ukraine',
  '5,484,936',
  '',
  '111,789                                ',
  '',
  '5,334,190'],
 ['Chile',
  '5,278,252',
  '',
  '64,497                                ',
  '',
  '5,211,301'],
 ['Malaysia',
  '5,056,911',
  '',
  '36,994                                ',
  '',
  '5,006,634'],
 ['Israel',
  '4,818,346',
  '',
  '12,416                                ',
  '',
  '4,798,473'],
 ['Belgium',
  '4,786,803',
  '',
  '34,166                                ',
  '',
  '4,723,282'],
 ['DPRK',
  '4,772,813',
  '',
  '74                                ',
  '',
  '4,772,739'],
 ['Thailand',
  '4,728,967',
  '',
  '33,940                                ',
  '',
  '4,692,636'],
 ['Canada',
  '4,641,301',
  '',
  '52,247                                ',
  '',
  '4,563,303'],
 ['Czechia',
  '4,637,897',
  '',
  '42,726                                ',
  '',
  '4,591,159'],
 ['Peru',
  '4,496,896',
  '',
  '219,991                                ',
  '',
  '4,273,686'],
 ['Switzerland',
  '4,400,218',
  '',
  '14,452                                ',
  '',
  '4,379,844'],
 ['Philippines',
  '4,085,539',
  '',
  '66,437                                ',
  '',
  '4,009,622'],
 ['South Africa',
  '4,075,849',
  '',
  '102,595                                ',
  '',
  '3,912,506'],
 ['Romania',
  '3,380,891',
  '',
  '67,961                                ',
  '',
  '3,299,960'],
 ['Denmark',
  '3,179,563',
  '',
  '8,464                                ',
  '',
  '3,169,944'],
 ['Hong Kong',
  '2,886,633',
  '',
  '13,490                                ',
  '',
  '2,870,397'],
 ['Sweden',
  '2,703,773',
  '',
  '23,928                                ',
  '',
  '2,676,426'],
 ['Serbia',
  '2,527,640',
  '',
  '18,002                                ',
  '',
  '2,498,044'],
 ['Iraq',
  '2,465,545',
  '',
  '25,375                                ',
  '',
  '2,439,497'],
 ['Singapore',
  '2,314,707',
  '',
  '1,727                                ',
  '',
  '2,149,583'],
 ['New Zealand',
  '2,286,481',
  '',
  '4,045                                ',
  '',
  '2,271,682'],
 ['Hungary',
  '2,200,211',
  '',
  '48,828                                ',
  '',
  '2,147,103'],
 ['Bangladesh',
  '2,038,091',
  '',
  '29,446                                ',
  '',
  '1,998,448'],
 ['Slovakia',
  '1,866,064',
  '',
  '21,141                                ',
  '',
  '1,844,330'],
 ['Georgia',
  '1,836,791',
  '',
  '17,032                                ',
  '',
  '1,776,548'],
 ['Jordan',
  '1,746,997',
  '',
  '14,122                                ',
  '',
  '1,731,007'],
 ['Ireland',
  '1,708,933',
  '',
  '8,810                                ',
  '',
  '1,696,485'],
 ['Pakistan',
  '1,580,429',
  '+20',
  '30,655                                ',
  '',
  '1,538,689'],
 ['Norway',
  '1,482,235',
  '',
  '5,213                                ',
  '',
  '1,475,779'],
 ['Finland',
  '1,469,865',
  '',
  '9,144                                ',
  '',
  '1,456,454'],
 ['Kazakhstan',
  '1,410,791',
  '',
  '13,848                                ',
  '',
  '1,383,020'],
 ['Slovenia',
  '1,342,491',
  '',
  '7,100                                ',
  '',
  '1,328,006'],
 ['Lithuania',
  '1,316,799',
  '',
  '9,650                                ',
  '',
  '1,303,244'],
 ['Bulgaria',
  '1,302,146',
  '',
  '38,288                                ',
  '',
  '1,260,996'],
 ['Morocco',
  '1,272,733',
  '',
  '16,296                                ',
  '',
  '1,256,151'],
 ['Croatia',
  '1,271,276',
  '',
  '18,091                                ',
  '',
  '1,252,694'],
 ['Guatemala',
  '1,246,722',
  '',
  '20,189                                ',
  '',
  '1,225,638'],
 ['Lebanon',
  '1,235,804',
  '',
  '10,885                                ',
  '',
  '1,087,587'],
 ['Costa Rica',
  '1,226,315',
  '',
  '9,326                                ',
  '',
  '860,711'],
 ['Bolivia',
  '1,196,464',
  '',
  '22,375                                ',
  '',
  '1,165,163'],
 ['Tunisia',
  '1,152,262',
  '',
  '29,367                                ',
  '',
  'N/A'],
 ['Cuba',
  '1,112,990',
  '',
  '8,530                                ',
  '',
  '1,104,340'],
 ['UAE',
  '1,060,146',
  '',
  '2,349                                ',
  '',
  '1,041,294'],
 ['Ecuador',
  '1,059,529',
  '',
  '36,017                                ',
  '',
  '1,022,992'],
 ['Uruguay',
  '1,037,095',
  '',
  '7,621                                ',
  '',
  '1,028,996'],
 ['Panama',
  '1,035,357',
  '',
  '8,617                                ',
  '',
  '1,026,192'],
 ['Mongolia',
  '1,007,943',
  '',
  '2,179                                ',
  '',
  '1,005,732'],
 ['Nepal',
  '1,002,128',
  '',
  '12,022                                ',
  '',
  '989,729'],
 ['Belarus',
  '994,037',
  '',
  '7,118                                ',
  '',
  '985,592'],
 ['Latvia',
  '977,282',
  '',
  '6,302                                ',
  '',
  '970,544'],
 ['Saudi Arabia',
  '838,246',
  '',
  '9,637                                ',
  '',
  '823,911'],
 ['Azerbaijan',
  '830,780',
  '',
  '10,212                                ',
  '',
  '820,094'],
 ['Paraguay',
  '809,269',
  '',
  '19,906                                ',
  '',
  'N/A'],
 ['Bahrain',
  '718,724',
  '',
  '1,559                                ',
  '',
  '716,589'],
 ['Sri Lanka',
  '672,103',
  '',
  '16,835                                ',
  '',
  '655,253'],
 ['Kuwait',
  '665,527',
  '',
  '2,570                                ',
  '',
  '660,237'],
 ['Dominican Republic',
  '660,937',
  '',
  '4,384                                ',
  '',
  '644,785'],
 ['Cyprus',
  '656,904',
  '',
  '1,350                                ',
  '',
  '653,364'],
 ['Myanmar',
  '634,154',
  '',
  '19,490                                ',
  '',
  '614,619'],
 ['Palestine',
  '621,008',
  '',
  '5,404                                ',
  '',
  '615,445'],
 ['Moldova',
  '619,510',
  '',
  '12,100                                ',
  '',
  '504,142'],
 ['Estonia',
  '617,222',
  '',
  '2,979                                ',
  '',
  '524,990'],
 ['Venezuela',
  '552,512',
  '',
  '5,856                                ',
  '',
  '546,421'],
 ['Egypt',
  '515,913',
  '',
  '24,613                                ',
  '',
  '442,182'],
 ['Libya',
  '507,244',
  '',
  '6,437                                ',
  '',
  '500,792'],
 ['Qatar',
  '503,909',
  '',
  '690                                ',
  '',
  '501,346'],
 ['Ethiopia',
  '500,774',
  '',
  '7,574                                ',
  '',
  '487,838'],
 ['Réunion',
  '486,588',
  '',
  '921                                ',
  '',
  '418,572'],
 ['Honduras',
  '472,485',
  '',
  '11,111                                ',
  '',
  'N/A'],
 ['Armenia',
  '448,707',
  '',
  '8,743                                ',
  '',
  '435,162'],
 ['Bosnia and Herzegovina',
  '402,636',
  '',
  '16,328                                ',
  '',
  '379,084'],
 ['Oman',
  '399,449',
  '',
  '4,628                                ',
  '',
  '384,669'],
 ['North Macedonia',
  '347,672',
  '',
  '9,667                                ',
  '',
  '337,068'],
 ['Zambia',
  '343,803',
  '',
  '4,058                                ',
  '',
  '339,632'],
 ['Kenya',
  '342,992',
  '',
  '5,688                                ',
  '',
  '337,282'],
 ['Albania',
  '334,714',
  '',
  '3,602                                ',
  '',
  '329,419'],
 ['Botswana',
  '329,837',
  '',
  '2,801                                ',
  '',
  '327,027'],
 ['Luxembourg',
  '297,757',
  '',
  '1,133                                ',
  '',
  '288,991'],
 ['Montenegro',
  '290,779',
  '',
  '2,820                                ',
  '',
  '287,276'],
 ['Brunei ',
  '284,632',
  '',
  '225                                ',
  '',
  '243,601'],
 ['Algeria',
  '271,642',
  '',
  '6,881                                ',
  '',
  '182,916'],
 ['Nigeria',
  '266,675',
  '',
  '3,155                                ',
  '',
  '259,953'],
 ['Zimbabwe',
  '264,584',
  '',
  '5,685                                ',
  '',
  '258,844'],
 ['Uzbekistan',
  '252,265',
  '',
  '1,637                                ',
  '',
  '241,486'],
 ['Mozambique',
  '233,334',
  '',
  '2,242                                ',
  '',
  '228,805'],
 ['Martinique',
  '229,807',
  '',
  '1,098                                ',
  '',
  'N/A'],
 ['Laos', '218,048', '', '758                                ', '', 'N/A'],
 ['Afghanistan',
  '212,605',
  '',
  '7,896                                ',
  '',
  '192,700'],
 ['Iceland', '209,191', '', '229                                ', '', 'N/A'],
 ['Kyrgyzstan',
  '206,849',
  '',
  '2,991                                ',
  '',
  '196,406'],
 ['Guadeloupe',
  '202,163',
  '',
  '1,012                                ',
  '',
  'N/A'],
 ['El Salvador',
  '201,785',
  '',
  '4,230                                ',
  '',
  '179,410'],
 ['Trinidad and Tobago',
  '191,257',
  '',
  '4,385                                ',
  '',
  '186,827'],
 ['Maldives',
  '185,894',
  '',
  '311                                ',
  '',
  '163,687'],
 ['Ghana',
  '171,589',
  '',
  '1,462                                ',
  '',
  '170,073'],
 ['Namibia',
  '171,222',
  '',
  '4,090                                ',
  '',
  '167,099'],
 ['Uganda',
  '170,610',
  '',
  '3,632                                ',
  '',
  '100,431'],
 ['Jamaica',
  '154,687',
  '',
  '3,532                                ',
  '',
  '102,678'],
 ['Cambodia',
  '138,726',
  '',
  '3,056                                ',
  '',
  '135,669'],
 ['Rwanda',
  '133,194',
  '',
  '1,468                                ',
  '',
  '131,647'],
 ['Cameroon',
  '124,834',
  '',
  '1,970                                ',
  '',
  '122,640'],
 ['Malta',
  '118,214',
  '',
  '833                                ',
  '',
  '116,744'],
 ['Barbados',
  '107,332',
  '',
  '582                                ',
  '',
  '106,739'],
 ['Angola',
  '105,353',
  '',
  '1,934                                ',
  '',
  '103,396'],
 ['Channel Islands',
  '101,717',
  '',
  '228                                ',
  '',
  '101,321'],
 ['French Guiana',
  '98,041',
  '',
  '420                                ',
  '',
  '11,254'],
 ['DRC', '95,945', '', '1,464                                ', '', '84,489'],
 ['Senegal',
  '88,978',
  '',
  '1,971                                ',
  '',
  '86,998'],
 ['Malawi',
  '88,717',
  '',
  '2,686                                ',
  '',
  '85,641'],
 ['Ivory Coast',
  '88,315',
  '',
  '834                                ',
  '',
  '87,473'],
 ['Suriname',
  '82,495',
  '',
  '1,404                                ',
  '',
  'N/A'],
 ['New Caledonia',
  '79,917',
  '',
  '314                                ',
  '',
  '79,600'],
 ['French Polynesia',
  '78,219',
  '',
  '649                                ',
  '',
  'N/A'],
 ['Eswatini',
  '74,520',
  '',
  '1,425                                ',
  '',
  '73,053'],
 ['Guyana',
  '73,121',
  '',
  '1,298                                ',
  '',
  '71,822'],
 ['Belize', '70,782', '', '688                                ', '', '70,085'],
 ['Fiji', '68,918', '', '883                                ', '', '67,026'],
 ['Madagascar',
  '68,105',
  '',
  '1,424                                ',
  '',
  '66,566'],
 ['Sudan',
  '63,922',
  '',
  '5,034                                ',
  '',
  '58,626'],
 ['Mauritania',
  '63,715',
  '',
  '997                                ',
  '',
  '62,471'],
 ['Cabo Verde',
  '63,281',
  '',
  '413                                ',
  '',
  '62,786'],
 ['Bhutan', '62,650', '', '21                                ', '', '61,564'],
 ['Syria',
  '57,508',
  '',
  '3,164                                ',
  '',
  '54,344'],
 ['Burundi', '53,719', '', '38                                ', '', '53,569'],
 ['Seychelles',
  '50,937',
  '',
  '172                                ',
  '',
  '50,750'],
 ['Gabon', '48,981', '', '306                                ', '', '48,674'],
 ['Andorra',
  '47,939',
  '',
  '165                                ',
  '',
  '47,563'],
 ['Papua New Guinea',
  '46,837',
  '',
  '670                                ',
  '',
  '43,982'],
 ['Curaçao',
  '45,986',
  '',
  '295                                ',
  '',
  '44,720'],
 ['Aruba', '44,114', '', '236                                ', '', '42,438'],
 ['Tanzania', '42,973', '', '846                                ', '', 'N/A'],
 ['Mayotte', '42,008', '', '188                                ', '', 'N/A'],
 ['Mauritius',
  '41,977',
  '',
  '1,043                                ',
  '',
  '40,208'],
 ['Togo', '39,470', '', '290                                ', '', '39,169'],
 ['Guinea', '38,280', '', '467                                ', '', '37,757'],
 ['Isle of Man',
  '38,008',
  '',
  '116                                ',
  '',
  'N/A'],
 ['Bahamas',
  '37,491',
  '',
  '833                                ',
  '',
  '36,366'],
 ['Lesotho',
  '34,790',
  '',
  '723                                ',
  '',
  '25,980'],
 ['Faeroe Islands',
  '34,658',
  '',
  '28                                ',
  '',
  'N/A'],
 ['Haiti', '34,218', '', '860                                ', '', '33,216'],
 ['Mali', '33,134', '', '743                                ', '', '32,312'],
 ['Cayman Islands',
  '31,472',
  '',
  '37                                ',
  '',
  '8,553'],
 ['Saint Lucia',
  '30,028',
  '',
  '409                                ',
  '',
  '29,095'],
 ['Benin', '28,014', '', '163                                ', '', '27,847'],
 ['Somalia',
  '27,334',
  '',
  '1,361                                ',
  '',
  '13,182'],
 ['Micronesia', '25,929', '', '65                                ', '', 'N/A'],
 ['Congo', '25,375', '', '386                                ', '', '24,006'],
 ['Solomon Islands',
  '24,575',
  '',
  '153                                ',
  '',
  'N/A'],
 ['San Marino',
  '23,873',
  '',
  '123                                ',
  '',
  '23,721'],
 ['Timor-Leste',
  '23,423',
  '',
  '138                                ',
  '',
  '23,102'],
 ['Burkina Faso',
  '22,056',
  '',
  '396                                ',
  '',
  '21,596'],
 ['Liechtenstein',
  '21,437',
  '',
  '91                                ',
  '',
  '21,345'],
 ['Gibraltar',
  '20,550',
  '',
  '113                                ',
  '',
  '16,579'],
 ['Grenada',
  '19,683',
  '',
  '238                                ',
  '',
  '19,358'],
 ['Bermuda',
  '18,860',
  '',
  '165                                ',
  '',
  '18,685'],
 ['Nicaragua',
  '18,491',
  '',
  '225                                ',
  '',
  '4,225'],
 ['South Sudan',
  '18,368',
  '',
  '138                                ',
  '',
  '18,115'],
 ['Tajikistan',
  '17,786',
  '',
  '125                                ',
  '',
  '17,264'],
 ['Equatorial Guinea',
  '17,229',
  '',
  '183                                ',
  '',
  '16,907'],
 ['Tonga', '16,814', '', '13                                ', '', '15,638'],
 ['Samoa', '16,737', '', '31                                ', '', '1,605'],
 ['Monaco', '16,178', '', '67                                ', '', '15,992'],
 ['Marshall Islands',
  '16,081',
  '',
  '17                                ',
  '',
  '15,954'],
 ['Dominica',
  '15,760',
  '',
  '74                                ',
  '',
  '15,673'],
 ['Djibouti',
  '15,690',
  '',
  '189                                ',
  '',
  '15,427'],
 ['CAR', '15,368', '', '113                                ', '', '15,200'],
 ['Gambia', '12,626', '', '372                                ', '', '12,189'],
 ['Saint Martin',
  '12,280',
  '',
  '63                                ',
  '',
  '1,399'],
 ['Vanuatu', '12,014', '', '14                                ', '', '11,976'],
 ['Greenland',
  '11,971',
  '',
  '21                                ',
  '',
  '2,761'],
 ['Yemen', '11,945', '', '2,159                                ', '', '9,124'],
 ['Caribbean Netherlands',
  '11,682',
  '',
  '38                                ',
  '',
  '10,476'],
 ['Sint Maarten',
  '11,030',
  '',
  '92                                ',
  '',
  '10,905'],
 ['Eritrea',
  '10,189',
  '',
  '103                                ',
  '',
  '10,086'],
 ['Niger', '9,931', '', '312                                ', '', '8,890'],
 ['St. Vincent Grenadines',
  '9,601',
  '',
  '124                                ',
  '',
  '9,472'],
 ['Guinea-Bissau',
  '9,350',
  '',
  '176                                ',
  '',
  '8,929'],
 ['Antigua and Barbuda',
  '9,106',
  '',
  '146                                ',
  '',
  '8,954'],
 ['Comoros', '9,093', '', '161                                ', '', '8,885'],
 ['Liberia', '8,090', '', '295                                ', '', '7,783'],
 ['Sierra Leone',
  '7,762',
  '',
  '126                                ',
  '',
  'N/A'],
 ['Chad', '7,696', '', '194                                ', '', '4,874'],
 ['British Virgin Islands',
  '7,305',
  '',
  '64                                ',
  '',
  'N/A'],
 ['Cook Islands',
  '7,050',
  '',
  '2                                ',
  '',
  '7,038'],
 ['Saint Kitts and Nevis',
  '6,598',
  '',
  '48                                ',
  '',
  '6,550'],
 ['Turks and Caicos',
  '6,565',
  '',
  '38                                ',
  '',

In [15]:
import pandas as pd

In [16]:
pd.DataFrame(data)

,0,1,2,3,4,5
0,USA,"106,464,679",,"1,158,158",,"104,311,698"
1,India,"44,808,022",,"531,091",,"44,223,211"
2,France,"39,896,203",,"166,024",,"39,592,740"
3,Germany,"38,382,386",,"171,992",,"38,149,200"
4,Brazil,"37,358,092",,"700,811",,"36,249,161"
...,...,...,...,...,...,...
226,Vatican City,29,,,,29
227,Western Sahara,10,,1,,9
228,MS Zaandam,9,,2,,7
229,Tokelau,5,,,,
230,China,"503,302",,"5,272",,"379,053"

In [17]:
column = ['Country','Total Cases','New Cases', 'Total Death', ' New Death','Total Recovered']

In [18]:
df = pd.DataFrame(data,columns = column)

In [19]:
df

,Country,Total Cases,New Cases,Total Death,New Death,Total Recovered
0,USA,"106,464,679",,"1,158,158",,"104,311,698"
1,India,"44,808,022",,"531,091",,"44,223,211"
2,France,"39,896,203",,"166,024",,"39,592,740"
3,Germany,"38,382,386",,"171,992",,"38,149,200"
4,Brazil,"37,358,092",,"700,811",,"36,249,161"
...,...,...,...,...,...,...
226,Vatican City,29,,,,29
227,Western Sahara,10,,1,,9
228,MS Zaandam,9,,2,,7
229,Tokelau,5,,,,
230,China,"503,302",,"5,272",,"379,053"

In [20]:
df.head() #prints first five rows

,Country,Total Cases,New Cases,Total Death,New Death,Total Recovered
0,USA,"106,464,679",,"1,158,158",,"104,311,698"
1,India,"44,808,022",,"531,091",,"44,223,211"
2,France,"39,896,203",,"166,024",,"39,592,740"
3,Germany,"38,382,386",,"171,992",,"38,149,200"
4,Brazil,"37,358,092",,"700,811",,"36,249,161"

In [21]:
df.tail() #prints last five rows

,Country,Total Cases,New Cases,Total Death,New Death,Total Recovered
226,Vatican City,29,,,,29
227,Western Sahara,10,,1,,9
228,MS Zaandam,9,,2,,7
229,Tokelau,5,,,,
230,China,"503,302",,"5,272",,"379,053"

In [22]:
type(df) #Objects of DataFrame

pandas.core.frame.DataFrame

In [23]:
df.to_csv('covid-data-16apr2023', index = False)

In [24]:
df= pd.read_csv('covid-data-16apr2023')

In [25]:
df

,Country,Total Cases,New Cases,Total Death,New Death,Total Recovered
0,USA,"106,464,679",NaN,"1,158,158",NaN,"104,311,698"
1,India,"44,808,022",NaN,"531,091",NaN,"44,223,211"
2,France,"39,896,203",NaN,"166,024",NaN,"39,592,740"
3,Germany,"38,382,386",NaN,"171,992",NaN,"38,149,200"
4,Brazil,"37,358,092",NaN,"700,811",NaN,"36,249,161"
...,...,...,...,...,...,...
226,Vatican City,29,NaN,,NaN,29
227,Western Sahara,10,NaN,1,NaN,9
228,MS Zaandam,9,NaN,2,NaN,7
229,Tokelau,5,NaN,,NaN,NaN
230,China,"503,302",NaN,"5,272",NaN,"379,053"

In [26]:
df.isna() # Checks missing value in a cell. True - missing; False - Not missing

     Country  Total Cases  New Cases  Total Death   New Death  Total Recovered
0      False        False       True        False        True            False
1      False        False       True        False        True            False
2      False        False       True        False        True            False
3      False        False       True        False        True            False
4      False        False       True        False        True            False
..       ...          ...        ...          ...         ...              ...
226    False        False       True        False        True            False
227    False        False       True        False        True            False
228    False        False       True        False        True            False
229    False        False       True        False        True             True
230    False        False       True        False        True            False

[231 rows x 6 columns]

In [27]:
df.shape

(231, 6)